/* 本地批量评估器：隐藏游戏表现层，但复用完整规则与自动玩家决策。 */
const AI_LAB_KEY="late-lantern-ai-lab-v2",AI_POLICY_KEY="late-lantern-ai-policy-v1",AI_ELITES_KEY="late-lantern-ai-elites-v1",AI_NEXT_MODE_KEY="late-lantern-ai-next-mode-v1";
const AI_LAB_LOCAL=/^(localhost|127\.0\.0\.1|\[::1\])$/.test(location.hostname)||location.protocol==="file:";
const AI_BASE_POLICY={name:"稳健基线",openCoverage:.42,crisisCoverage:.82,hireCoinBuffer:8,hireWeeks:1,repairNormal:.82,repairCrisis:.5,recruitDecorBonus:8};
const AI_POLICY_VARIANTS=[AI_BASE_POLICY,{...AI_BASE_POLICY,name:"积极招聘",hireCoinBuffer:2,recruitDecorBonus:14},{...AI_BASE_POLICY,name:"精打细算",openCoverage:.48,hireCoinBuffer:5,repairNormal:.76},{...AI_BASE_POLICY,name:"门铃优先",openCoverage:.32,crisisCoverage:.68},{...AI_BASE_POLICY,name:"库存优先",openCoverage:.55,crisisCoverage:.88},{...AI_BASE_POLICY,name:"防风稳健",repairNormal:.88,repairCrisis:.62},{...AI_BASE_POLICY,name:"现金进攻",repairNormal:.7,hireCoinBuffer:0,openCoverage:.36},{...AI_BASE_POLICY,name:"招募稳健",hireCoinBuffer:6,recruitDecorBonus:12,repairNormal:.8},{...AI_BASE_POLICY,name:"危机交易",crisisCoverage:.62,openCoverage:.4},{...AI_BASE_POLICY,name:"平衡二代",openCoverage:.4,crisisCoverage:.74,hireCoinBuffer:4,recruitDecorBonus:10,repairNormal:.8}];
const AI_STAFF_BASE={...AI_BASE_POLICY,name:"团队稳健",staffTarget:8,hireMinDeals:3,hireCreditFloor:3,hireCrisisLimit:4,payrollReserveWeeks:2,dismissMorale:14,recruitDecorBonus:14};
const AI_STAFF_POLICY_VARIANTS=[AI_STAFF_BASE,{...AI_STAFF_BASE,name:"快速成队",staffTarget:9,hireMinDeals:2,hireCoinBuffer:2,payrollReserveWeeks:1},{...AI_STAFF_BASE,name:"八人稳守",staffTarget:8,hireMinDeals:4,payrollReserveWeeks:3,dismissMorale:18},{...AI_STAFF_BASE,name:"人才广纳",staffTarget:10,hireCreditFloor:2,hireCrisisLimit:5,recruitDecorBonus:20},{...AI_STAFF_BASE,name:"工资保守",staffTarget:8,hireCoinBuffer:14,payrollReserveWeeks:3},{...AI_STAFF_BASE,name:"士气优先",staffTarget:9,dismissMorale:22,payrollReserveWeeks:2},{...AI_STAFF_BASE,name:"危机不停招",staffTarget:8,hireCrisisLimit:6,hireCreditFloor:2},{...AI_STAFF_BASE,name:"小步扩张",staffTarget:8,hireMinDeals:5,hireCoinBuffer:8},{...AI_STAFF_BASE,name:"九人轮班",staffTarget:9,payrollReserveWeeks:2,dismissMorale:16},{...AI_STAFF_BASE,name:"团队进攻",staffTarget:10,hireMinDeals:2,hireCoinBuffer:0,payrollReserveWeeks:1,recruitDecorBonus:18}];
const AI_LAB_MODES={lean:{name:"低地最会经营的小店",objective:"先满足原年度过关条件；过关状态相同时，最终钱箱越多越好。"},staff:{name:"店员之家",objective:"过关条件不变；优先不亏钱，再最大化顾客满意度。"},storm:{name:"风暴守望者",objective:"先满足年度防御目标，再比较坚固度、灾害数与钱箱。"},story:{name:"低地故事屋",objective:"优先解锁两位特殊来客，再比较解锁进度、好感与钱箱。"},free:{name:"自由游戏",objective:"没有过关线，比较存活天数与最终钱箱。"}};
function aiLabRead(){try{return JSON.parse(localStorage.getItem(AI_LAB_KEY))||{running:false,results:[]}}catch{return {running:false,results:[]}}}
function aiLabWrite(data){localStorage.setItem(AI_LAB_KEY,JSON.stringify(data))}
function aiLabElites(){try{return JSON.parse(localStorage.getItem(AI_ELITES_KEY))||{}}catch{return {}}}
function aiLabPolicyKey(policy){return [policy.openCoverage,policy.crisisCoverage,policy.hireCoinBuffer,policy.hireWeeks,policy.payrollReserveWeeks,policy.staffTarget,policy.hireMinDeals,policy.hireCreditFloor,policy.hireCrisisLimit,policy.dismissMorale,policy.repairNormal,policy.repairCrisis,policy.recruitDecorBonus].join("|")}
function aiLabClamp(value,min,max){return Math.max(min,Math.min(max,value))}
function aiLabMutation(base,index,mode){const direction=index%2?1:-1,scale=1+Math.floor(index/2),next={...base,name:`${base.name.replace(/ · .*/,"")} · 迭代${index+1}`,openCoverage:aiLabClamp(base.openCoverage+direction*.025*scale,.25,.65),crisisCoverage:aiLabClamp(base.crisisCoverage-direction*.025,.55,.95),hireCoinBuffer:aiLabClamp(base.hireCoinBuffer-direction*2,0,20),repairNormal:aiLabClamp(base.repairNormal+direction*.025,.65,.95),repairCrisis:aiLabClamp(base.repairCrisis+direction*.03,.3,.75),recruitDecorBonus:aiLabClamp(base.recruitDecorBonus-direction*2,4,22)};if(mode==="staff")Object.assign(next,{staffTarget:aiLabClamp((base.staffTarget??8)+(index%3===0?1:index%3===1?-1:0),8,11),hireMinDeals:aiLabClamp((base.hireMinDeals??3)+direction,1,7),hireCreditFloor:aiLabClamp((base.hireCreditFloor??3)+(index%3===0?1:index%3===1?-1:0),1,4),hireCrisisLimit:aiLabClamp((base.hireCrisisLimit??4)+direction,2,6),payrollReserveWeeks:aiLabClamp((base.payrollReserveWeeks??2)+(index%3===0?1:index%3===1?-1:0),1,3),dismissMorale:aiLabClamp((base.dismissMorale??14)+direction*2,6,26)});return next}
function aiLabPoliciesFor(mode){const elites=aiLabElites()[mode]||[],initial=mode==="staff"?AI_STAFF_POLICY_VARIANTS:AI_POLICY_VARIANTS;if(!elites.length)return initial.map(policy=>({...policy}));const policies=elites.slice(0,3).map((policy,index)=>({...policy,name:`精英 ${index+1} · ${policy.name.replace(/^精英 \d+ · /,"")}`}));for(let index=0;policies.length<10;index++)policies.push(aiLabMutation(elites[index%elites.length],index,mode));return policies}
function aiLabSaveElites(lab){const ranked=[...(lab.results||[])].sort(aiLabCompare),seen=new Set(),top=[];for(const row of ranked){const key=aiLabPolicyKey(row.policy);if(seen.has(key))continue;seen.add(key);top.push(row.policy);if(top.length===3)break}const all=aiLabElites();all[lab.mode]=top;localStorage.setItem(AI_ELITES_KEY,JSON.stringify(all));lab.elites=top}
function activeAIPolicy(){const lab=aiLabRead();if(lab.running&&lab.policy)return lab.policy;try{return JSON.parse(localStorage.getItem(AI_POLICY_KEY))||AI_BASE_POLICY}catch{return AI_BASE_POLICY}}
window.LateLanternAILab={fast:false,policy:activeAIPolicy};
const aiLabSaveBefore=save;save=function(){if(!window.LateLanternAILab?.fast)return aiLabSaveBefore()};
/* 批量模式不生成与决策无关的 DOM。保留 inventory/shop/day-flow/map 渲染供策略读取。 */
const aiLabRenderWeatherBefore=renderWeatherEffect;renderWeatherEffect=function(cal){if(!window.LateLanternAILab?.fast)return aiLabRenderWeatherBefore(cal)};
const aiLabRenderUnlocksBefore=renderUnlocks;renderUnlocks=function(){if(!window.LateLanternAILab?.fast)return aiLabRenderUnlocksBefore()};
const aiLabRenderForecastBefore=renderForecast;renderForecast=function(){if(!window.LateLanternAILab?.fast)return aiLabRenderForecastBefore()};
const aiLabRenderTomorrowBefore=renderTomorrowForecast;renderTomorrowForecast=function(){if(!window.LateLanternAILab?.fast)return aiLabRenderTomorrowBefore()};
const aiLabRenderQuickBefore=renderQuickInventory;renderQuickInventory=function(){if(!window.LateLanternAILab?.fast)return aiLabRenderQuickBefore()};
const aiLabRenderRelationsBefore=renderRelationships;renderRelationships=function(){if(!window.LateLanternAILab?.fast)return aiLabRenderRelationsBefore()};
const aiLabRenderHistoryBefore=renderHistory;renderHistory=function(){if(!window.LateLanternAILab?.fast)return aiLabRenderHistoryBefore()};
const aiLabRenderLogBefore=renderLog;renderLog=function(){if(!window.LateLanternAILab?.fast)return aiLabRenderLogBefore()};
const aiLabRenderStaffBefore=renderStaff;renderStaff=function(){if(!window.LateLanternAILab?.fast)return aiLabRenderStaffBefore()};

function aiLabSnapshot(mode){
  ensureModeStats();const total=fortressTotals(),integrity=total.max?Math.round(total.health/total.max*100):0,noBroken=Object.values(state.fortress.parts).every(part=>part.health>0),noDebt=state.employees.every(employee=>!employee.debt),avgMorale=state.employees.length?Math.round(state.employees.reduce((sum,e)=>sum+ensureEmployeeMorale(e).morale,0)/state.employees.length):0,special=typeof SPECIAL_NAMES!=="undefined"?SPECIAL_NAMES.filter(name=>state.metCustomers.includes(name)).length:0;
  let passed=false,modeScore=state.coins,scoreLabel=`钱箱 ${state.coins}`;
  if(mode==="lean"){passed=state.modeStats.maxEmployees<=3&&state.modeStats.revenue>=220&&integrity>=80&&noBroken&&noDebt&&(state.survival?.credit??5)>=4;modeScore=state.coins;scoreLabel=`钱箱 ${state.coins} · 收入 ${state.modeStats.revenue}`}
  if(mode==="staff"){const satisfaction=customerSatisfactionScore(),financialHealthy=modeFinanciallyHealthy();passed=state.employees.length>=8&&avgMorale>=60&&noDebt&&(state.survival?.credit??5)>=4;modeScore=(financialHealthy?1000000:0)+satisfaction*1000+Math.max(0,state.coins-state.modeStats.periodStartCoins);scoreLabel=`满意度 ${satisfaction} · ${financialHealthy?"未亏损":"亏损"}`;return {passed,modeScore,scoreLabel,integrity,avgMorale,special,satisfaction,financialHealthy}}
  if(mode==="storm"){passed=state.modeStats.disasters>=8&&integrity>=80&&noBroken;modeScore=integrity*100+state.modeStats.disasters*10+state.coins;scoreLabel=`坚固 ${integrity}% · 灾害 ${state.modeStats.disasters}`}
  if(mode==="story"){passed=special>=2;modeScore=special*10000+state.metCustomers.length*100+state.coins;scoreLabel=`特殊来客 ${special}/2 · 已识 ${state.metCustomers.length}`}
  if(mode==="free"){passed=true;modeScore=state.day*1000+state.coins;scoreLabel=`存活 ${state.day} 天 · 钱箱 ${state.coins}`}
  return {passed,modeScore,scoreLabel,integrity,avgMorale,special};
}
function aiLabPassed(row){return ["lean","staff","storm"].includes(row.mode)&&row.result!=="horizon"?false:!!row.passed}
function aiLabCompare(a,b){const pass=Number(aiLabPassed(b))-Number(aiLabPassed(a));if(pass)return pass;if(a.mode==="staff"&&b.mode==="staff"){const finance=Number(!!b.financialHealthy)-Number(!!a.financialHealthy);if(finance)return finance;const satisfaction=(b.satisfaction||0)-(a.satisfaction||0);if(satisfaction)return satisfaction}return b.modeScore-a.modeScore||b.coins-a.coins||b.day-a.day}
function aiLabRenderLive(){
  const lab=aiLabRead(),panel=document.querySelector("#aiLabLive");if(!panel||!lab.running)return;panel.hidden=false;const completed=lab.results?.length||0,currentFraction=Math.min(1,(state.day||1)/(lab.horizon||336)),total=fortressTotals(),integrity=total.max?Math.round(total.health/total.max*100):0,weak=Object.entries(state.fortress.parts).sort(([,a],[,b])=>a.health/a.max-b.health/b.max)[0],credit=state.survival?.credit??5,noTrade=state.survival?.noTradeDays||0;document.querySelector("#aiLabLiveTitle").textContent=`${AI_LAB_MODES[lab.mode].name} · ${lab.policy.name}`;document.querySelector("#aiLabLiveCount").textContent=`${completed} / ${lab.total}`;document.querySelector("#aiLabLiveBar").style.width=`${((completed+currentFraction)/lab.total)*100}%`;document.querySelector("#aiLabLiveStatus").textContent=`第 ${completed+1} 局计算中 · 模拟到第 ${state.day||1} / ${lab.horizon} 天 · 当前钱箱 ${state.coins||0} 枚`;
  document.querySelector("#aiLabLiveVitals").innerHTML=`<article><small>员工</small><strong>${state.employees.length} 位</strong><em>峰值 ${state.modeStats?.maxEmployees||state.employees.length}</em></article><article><small>房屋坚固度</small><strong>${integrity}%</strong><em>${SHOP_PARTS[weak[0]].name}最弱 · ${weak[1].health}/${weak[1].max}</em></article><article class="${credit<=2||noTrade>=4?"danger":""}"><small>信用与经营</small><strong>${credit} / 5</strong><em>连续无交易 ${noTrade}/7 天</em></article>${lab.mode==="staff"?`<article class="${modeFinanciallyHealthy()?"":"danger"}"><small>顾客满意度</small><strong>${customerSatisfactionScore()} / 100</strong><em>${modeFinanciallyHealthy()?"经营未亏损":"钱箱低于年初或有欠薪"}</em></article>`:`<article><small>年度经营收入</small><strong>${state.modeStats?.revenue||0}</strong><em>钱箱 ${state.coins} 枚</em></article>`}`;
  const rows=lab.results||[];document.querySelector("#aiLabLiveRows").innerHTML=rows.length?rows.map((row,index)=>`<tr class="${index===rows.length-1?"latest":""}"><td>${row.run}</td><td>${row.policy.name}</td><td>${aiLabPassed(row)?"✓ 通过":"— 未通过"}</td><td>${row.day}</td><td><strong>${row.coins}</strong></td><td>${row.scoreLabel}</td></tr>`).join(""):`<tr><td colspan="6">第一局计算中……</td></tr>`;
  const pause=document.querySelector("#aiLabLivePause");if(pause)pause.textContent=lab.paused?"继续实验":"暂停实验";if(lab.paused)document.querySelector("#aiLabLiveStatus").textContent=`实验已暂停 · 第 ${completed+1} 局、第 ${state.day||1} 天 · 可以继续、结束或重新运行`;
}
function aiLabFinish(result){const lab=aiLabRead();if(!lab.running||lab.finishing)return;lab.finishing=true;const metric=aiLabSnapshot(lab.mode);lab.results.push({run:lab.index+1,mode:lab.mode,policy:lab.policy,result,day:state.day,coins:state.coins,revenue:state.modeStats?.revenue||0,deals:totalDeals(),visits:totalVisits(),employees:state.employees.length,maxEmployees:state.modeStats?.maxEmployees||state.employees.length,...metric});lab.index++;lab.finishing=false;if(lab.index>=lab.total){lab.running=false;lab.completed=true;aiLabSaveElites(lab)}else{lab.policies||=AI_POLICY_VARIANTS.map(policy=>({...policy}));lab.policy=lab.policies[lab.index]}aiLabWrite(lab);stopAutoplay("本轮实验完成");localStorage.removeItem("late-lantern-save");location.hash="ai-lab";setTimeout(()=>location.reload(),25)}

function aiLabRender(){
  if(!AI_LAB_LOCAL)return;document.querySelector("#aiLabNav").hidden=false;const lab=aiLabRead(),rows=lab.results||[],body=document.querySelector("#aiLabResults"),progress=document.querySelector("#aiLabProgress"),summary=document.querySelector("#aiLabSummary"),adopt=document.querySelector("#aiLabAdopt"),stop=document.querySelector("#aiLabStop"),modeSelect=document.querySelector("#aiLabMode"),savedNext=localStorage.getItem(AI_NEXT_MODE_KEY),mode=lab.running?lab.mode:(AI_LAB_MODES[savedNext]?savedNext:lab.mode||"lean");
  if(modeSelect&&!lab.running&&document.activeElement!==modeSelect)modeSelect.value=mode;document.querySelector("#aiLabModeTitle").textContent=`${AI_LAB_MODES[mode].name} · 10 局`;document.querySelector("#aiLabObjective").textContent=AI_LAB_MODES[mode].objective;
  if(body)body.innerHTML=rows.length?rows.map(row=>{const passed=aiLabPassed(row);return `<tr><td>${row.run}</td><td class="strategy-name">${row.policy.name}</td><td><span class="lab-pass ${passed?"passed":"failed"}">${passed?"✓ 通过":"— 未通过"}</span></td><td class="result-reason">${row.result==="horizon"?"完成评估":"失败 · "+row.result}</td><td>${row.day}</td><td><strong>${row.coins}</strong></td><td class="mode-score">${row.scoreLabel}</td><td>${row.deals}</td><td>${row.maxEmployees}</td><td>${row.integrity}%</td></tr>`}).join(""):`<tr><td colspan="10">还没有本地实验记录。</td></tr>`;
  if(progress){progress.hidden=!lab.running;progress.innerHTML=lab.running?`<span>无动画批量模拟中</span><strong>第 ${lab.index+1} / ${lab.total} 局 · ${lab.policy.name}</strong><i><b style="width:${((lab.index+(state.day||1)/(lab.horizon||336))/lab.total)*100}%"></b></i><small>${AI_LAB_MODES[lab.mode].name} · 当前第 ${state.day||1} 天 · 钱箱 ${state.coins||0}</small>`:""}if(stop)stop.hidden=!lab.running;
  if(rows.length){const ranked=[...rows].sort(aiLabCompare),top=ranked.slice(0,3),passed=rows.filter(aiLabPassed).length;summary.innerHTML=top.map((row,index)=>`<article><small>保留策略 ${index+1}</small><strong>${row.policy.name}</strong><em>${aiLabPassed(row)?"已过关":"未过关"} · ${row.scoreLabel}</em></article>`).join("")+`<article><small>本批过关率</small><strong>${passed} / ${rows.length}</strong><em>${lab.completed?"前三名已成为下一批种子":"实验仍在进行"}</em></article>`;adopt.hidden=!lab.completed}else summary.innerHTML="";
}
function aiLabBegin(){const horizon=Math.max(28,Math.min(672,Number(document.querySelector("#aiLabHorizon")?.value)||336)),mode=document.querySelector("#aiLabMode")?.value||"lean",policies=aiLabPoliciesFor(mode);if(!confirm(`将清除当前游戏存档，并在后台快速运行 10 局「${AI_LAB_MODES[mode].name}」、每局最多 ${horizon} 天。${aiLabElites()[mode]?.length?"本批会从上次前三名继续迭代。":"本批从初始策略开始。"}继续吗？`))return;aiLabWrite({running:true,paused:false,index:0,total:10,horizon,mode,results:[],policies,policy:policies[0]});localStorage.removeItem("late-lantern-save");location.hash="ai-lab";location.reload()}
function aiLabResume(){const lab=aiLabRead();if(!AI_LAB_LOCAL||!lab.running){document.documentElement.classList.remove("ai-lab-booting");return}window.LateLanternAILab.fast=true;window.LateLanternAILab.policy=()=>lab.policy;window.LateLanternAIData=null;document.documentElement.classList.remove("ai-lab-booting");document.body.classList.add("ai-lab-running");if(!state.gameMode)chooseGameMode(lab.mode);document.querySelector("#modeSelectDialog")?.close();document.querySelectorAll("#weatherLayer,#potentialVisitors,#quickInventory,#relationshipGrid,#historyList,#guestStats,#logSummary").forEach(node=>node.replaceChildren());aiLabRenderLive();if(!lab.paused)startAutoplay()}
const aiLabTriggerBefore=triggerGameOver;triggerGameOver=function(type){if(aiLabRead().running){aiLabFinish(type);return}aiLabTriggerBefore(type)};
const aiLabNextDayBefore=nextDay;nextDay=function(force=false){const before=state.day;aiLabNextDayBefore(force);const lab=aiLabRead();if(lab.running&&state.day!==before){aiLabRenderLive();window.LateLanternAILab.yieldNow=true;if(state.day>=lab.horizon)aiLabFinish("horizon")}};
document.querySelector("#aiLabMode")?.addEventListener("change",event=>{const mode=event.target.value;if(!AI_LAB_MODES[mode])return;localStorage.setItem(AI_NEXT_MODE_KEY,mode);document.querySelector("#aiLabModeTitle").textContent=`${AI_LAB_MODES[mode].name} · 10 局`;document.querySelector("#aiLabObjective").textContent=AI_LAB_MODES[mode].objective});document.querySelector("#aiLabStart")?.addEventListener("click",aiLabBegin);document.querySelector("#aiLabStop")?.addEventListener("click",()=>{const lab=aiLabRead();lab.running=false;aiLabWrite(lab);window.LateLanternAILab.fast=false;document.body.classList.remove("ai-lab-running");stopAutoplay("实验已停止");aiLabRender()});document.querySelector("#aiLabClear")?.addEventListener("click",()=>{localStorage.removeItem(AI_LAB_KEY);aiLabRender()});document.querySelector("#aiLabAdopt")?.addEventListener("click",()=>{const rows=aiLabRead().results||[],best=[...rows].sort(aiLabCompare)[0];if(best){localStorage.setItem(AI_POLICY_KEY,JSON.stringify(best.policy));window.LateLanternAILab.policy=()=>best.policy;alert(`已采用「${best.policy.name}」。普通自动玩家也会使用这组权重。`)}});
document.querySelector("#aiLabLivePause")?.addEventListener("click",()=>{const lab=aiLabRead();if(!lab.running)return;lab.paused=!lab.paused;aiLabWrite(lab);if(lab.paused){aiLabSaveBefore();stopAutoplay("批量实验已暂停")}else startAutoplay();aiLabRenderLive()});
document.querySelector("#aiLabLiveStop")?.addEventListener("click",()=>{const lab=aiLabRead();lab.running=false;lab.paused=false;lab.completed=true;aiLabWrite(lab);stopAutoplay("批量实验已结束");localStorage.removeItem("late-lantern-save");location.hash="ai-lab";location.reload()});
document.querySelector("#aiLabLiveRestart")?.addEventListener("click",()=>{if(!confirm("确定放弃当前批次的结果，并从第一局重新运行吗？"))return;const old=aiLabRead(),mode=old.mode||"lean",policies=aiLabPoliciesFor(mode);aiLabWrite({running:true,paused:false,index:0,total:10,horizon:old.horizon||336,mode,results:[],policies,policy:policies[0]});stopAutoplay("正在重新开始实验");localStorage.removeItem("late-lantern-save");location.hash="ai-lab";location.reload()});
if(AI_LAB_LOCAL){const initialLab=aiLabRead();if(initialLab.completed)location.hash="ai-lab";if(location.hash==="#ai-lab"&&!initialLab.running){showPage("ai-lab");setTimeout(()=>{document.querySelector("#modeSelectDialog")?.close();showPage("ai-lab")},320)}aiLabRender();setTimeout(aiLabResume,220)}
