const CHAPTERS=[
 {id:1,start:1,name:"初燃的灯",note:"门铃第一次为陌生的故事响起"},
 {id:2,start:8,name:"雾中的街",note:"你开始亲手布置这间会呼吸的小店"},
 {id:3,start:15,name:"星落之夜",note:"客人与交易被写进一本不会遗忘的日志"},
 {id:4,start:22,name:"会自己排列的货架",note:"货架开始显露主动制作商品的方法"},
 {id:5,start:29,name:"门铃响了两次",note:"屋檐上的风向针开始预告明日天气"},
 {id:6,start:36,name:"没有寄件人的信",note:"打烊后可以为明日调整柜台展示"},
 {id:7,start:43,name:"雨水记得名字",note:"预报里开始浮现可能来访的身影"},
 {id:8,start:50,name:"影子来买东西",note:"熟悉的客人终于让你读懂他们的喜恶"},
 {id:9,start:57,name:"被遗忘的橱窗",note:"雾里有一扇橱窗，映出的却不是现在的店"},
 {id:10,start:64,name:"上一任店主",note:"旧账本的夹页里，出现了上一任店主留下的名字"},
 {id:11,start:71,name:"倒着开放的花",note:"一朵从黄昏向清晨开放的花被送到门前"},
 {id:12,start:78,name:"春天最后的委托",note:"春季将尽，一份来得太迟的委托仍在等待答复"},
 {id:13,start:85,name:"春末灯市",note:"迟灯巷挂起成排纸灯，街道比往常热闹了一夜"},
 {id:14,start:92,name:"不肯落下的太阳",note:"日暮迟迟不来，影子们开始失去回家的方向"},
 {id:15,start:99,name:"瓶中的海潮",note:"柜台上的玻璃瓶每到夜里便传出潮汐声"},
 {id:16,start:106,name:"借来的名字",note:"一位客人想赎回那个曾经借给别人的名字"},
 {id:17,start:113,name:"会做梦的商品",note:"打烊后，货架上的商品开始说起同一个梦"},
 {id:18,start:120,name:"第十三把钥匙",note:"钥匙串上多出了一把谁也不记得配过的钥匙"},
 {id:19,start:127,name:"门后的车站",note:"仓库门后传来汽笛，那里本不该有一座车站"},
 {id:20,start:134,name:"永远误点的列车",note:"一列从未准点抵达的列车终于亮起了灯"},
 {id:21,start:141,name:"售票员的账本",note:"账本记录着每位旅人真正想去的地方"},
 {id:22,start:148,name:"没有终点的旅人",note:"有人带着一张没有终点站的车票来到店里"},
 {id:23,start:155,name:"太阳的碎屑",note:"金色碎屑从屋檐落下，摸起来仍有余温"},
 {id:24,start:162,name:"被偷走的黄昏",note:"迟灯巷突然失去了黄昏，只剩白昼与深夜"},
 {id:25,start:169,name:"站台上的店主",note:"废弃站台尽头，站着一个与你十分相似的人"},
 {id:26,start:176,name:"夏末长昼祭",note:"长昼结束前，巷里的居民决定点亮所有灯火"},
 {id:27,start:183,name:"同一本故事",note:"不同客人带来的故事，竟写在同一本旧书里"},
 {id:28,start:190,name:"乌鸦的收藏室",note:"阿墨终于邀请你去看那间从不示人的收藏室"},
 {id:29,start:197,name:"写错的结局",note:"故事的最后一页被人改写，客人们开始忘记归途"},
 {id:30,start:204,name:"迟到二十年的回信",note:"雨巷邮差带回了一封迟到了整整二十年的回信"},
 {id:31,start:211,name:"不存在的第六位客人",note:"客簿每到午夜便多出一行无人认识的字迹"},
 {id:32,start:218,name:"月亮背面的字",note:"满月背面藏着一段只有小店窗户能照见的文字"},
 {id:33,start:225,name:"店主不能完成的愿望",note:"第一次，有一件商品连你也无法制作"},
 {id:34,start:232,name:"被交换的记忆",note:"客人们发现彼此记住了不属于自己的往事"},
 {id:35,start:239,name:"空白的客簿",note:"所有名字在一夜之间从客簿上消失了"},
 {id:36,start:246,name:"她曾经来过",note:"陌生的笔迹坚持说，有个人其实一直都在这里"},
 {id:37,start:253,name:"黄昏收藏家",note:"收藏黄昏的人第一次亲自推开了店门"},
 {id:38,start:260,name:"拒绝出售的代价",note:"有些商品一旦留下，就会向店主索取代价"},
 {id:39,start:267,name:"秋末无月夜",note:"没有月亮的夜里，迟灯巷的出口悄然关闭"},
 {id:40,start:274,name:"第一场没有声音的雪",note:"冬雪落下，却吞没了街上所有的声音"},
 {id:41,start:281,name:"封在冰里的门铃",note:"冰层深处传来一声很久以前的门铃"},
 {id:42,start:288,name:"星星开始熄灭",note:"夜空中的星辰一颗接一颗失去了光"},
 {id:43,start:295,name:"上一任店主的房间",note:"第十三把钥匙终于打开了阁楼尽头的房门"},
 {id:44,start:302,name:"写给小店的委托",note:"这一次，委托单上的客人名字写着迟灯杂货铺"},
 {id:45,start:309,name:"第四枚灯芯",note:"店灯里藏着一枚从未被点燃过的灯芯"},
 {id:46,start:316,name:"被归还的商品",note:"售出的商品陆续回到货架，却不再是原来的模样"},
 {id:47,start:323,name:"五十二个空格",note:"旧账本留下五十二个空格，正等待被逐一填满"},
 {id:48,start:330,name:"黄昏收藏家的愿望",note:"收藏家愿用所有黄昏交换一个平凡的明天"},
 {id:49,start:337,name:"世界遗忘迟灯巷",note:"巷外的人不再记得这里曾有一间奇怪的小店"},
 {id:50,start:344,name:"今夜不做生意",note:"你第一次挂起歇业牌，只为认真听完一个故事"},
 {id:51,start:351,name:"最后一位客人",note:"门铃在深夜响起，一位等待许久的客人站在门外"},
 {id:52,start:358,name:"灯亮到明天",note:"最后一页写完了，但迟灯杂货铺仍会在明天亮灯"}
];
const LEGACY_VISIT_RULES={
 "栗尾先生":[{favor:0,weekday:[3],label:"每周三"},{favor:4,season:["summer"],label:"好感 4：夏季也会来"}],
 "阿墨":[{favor:0,moon:["full"],label:"满月之夜"},{favor:0,weekday:[6],label:"每周六"},{favor:5,season:["autumn"],label:"好感 5：秋季也会来"}],
 "雨巷邮差":[{favor:0,season:["spring"],label:"春季"},{favor:4,month:[2],label:"好感 4：每季第二个月"}],
 "钟婆婆":[{favor:0,weekday:[1],label:"每周一"},{favor:5,season:["winter"],label:"好感 5：冬季也会来"}],
 "瞌睡的獾":[{favor:0,season:["winter"],label:"冬季"},{favor:3,moon:["new"],label:"好感 3：新月之夜"}],
 "没有影子的小姐":[{favor:0,moon:["new"],label:"新月之夜"},{favor:0,weekday:[5],label:"每周五"},{favor:6,season:["winter"],label:"好感 6：冬季也会来"}],
 "贝壳里的男孩":[{favor:0,season:["summer"],label:"夏季"},{favor:0,weekday:[7],label:"每周日"},{favor:4,month:[1],label:"好感 4：每季第一个月"}],
 "雾鹿女士":[{favor:0,season:["autumn"],moon:["full"],label:"秋季的满月"},{favor:0,weekday:[2],label:"每周二"},{favor:5,season:["autumn"],label:"好感 5：整个秋季"}],
 "失眠的云":[{favor:0,month:[2],label:"每季第二个月"},{favor:4,moon:["waning"],label:"好感 4：亏月期间"}],
 "北斗船长":[{favor:0,season:["spring"],month:[3],label:"春季第三个月"},{favor:0,weekday:[4],label:"每周四"},{favor:5,moon:["waxing"],label:"好感 5：盈月期间"}],
 "衔火的蛾":[{favor:0,season:["summer"],moon:["full"],label:"夏季的满月"},{favor:5,season:["summer"],label:"好感 5：整个夏季"}],
 "最后一颗星":[{favor:0,season:["winter"],moon:["new"],label:"冬季的新月"},{favor:7,season:["winter"],label:"好感 7：整个冬季"}]
};
const LEGACY_ITEMS={"捕风瓶":{chapter:1,icon:"🏺",note:"瓶口偶尔传来口哨声",recipe:{"月光碎片":1,"空玻璃瓶":1}}};
const LEGACY_MATERIALS={"月光碎片":{chapter:1,icon:"🌙",note:"薄而冷的微光"}};
Object.assign(LEGACY_ITEMS,{
 "无声剪刀":{chapter:1,icon:"✂️",note:"剪开布匹时像影子一样安静",recipe:{"银线":1,"旧木片":1}},
 "温度墨水":{chapter:2,icon:"🖋️",note:"写下的字摸起来像一双手",recipe:{"月光碎片":1,"雾盐":1}},
 "遗忘粉笔":{chapter:3,icon:"🧑‍🏫",note:"只擦去别人强加的坏话",recipe:{"星砂":1,"记忆蜡":1}},
 "钥匙糖":{chapter:2,icon:"🍬",note:"含在嘴里会想起一扇门",recipe:{"雾盐":1,"月光碎片":1}},
 "水面鞋":{chapter:3,icon:"👞",note:"鞋底踩在世界的倒面",recipe:{"银线":2,"星砂":1}},
 "不融冰":{chapter:2,icon:"🧊",note:"只有回到故乡才会融化",recipe:{"雾盐":2,"月光碎片":1}},
 "归巢铃":{chapter:3,icon:"🔔",note:"无论多远都能听见家的方向",recipe:{"铜齿轮":1,"回声贝壳":1}},
 "慢时喷壶":{chapter:3,icon:"🚿",note:"浇过的地方会慢慢长大",recipe:{"铜齿轮":1,"雾盐":2}},
 "逆流梳":{chapter:3,icon:"🪮",note:"能把河水梳回源头",recipe:{"回声贝壳":1,"银线":2}},
 "月文字帖":{chapter:3,icon:"📜",note:"字迹只在月光下显现",recipe:{"星砂":1,"月光碎片":2}},
 "星火盐罐":{chapter:3,icon:"🏺",note:"一小撮就能调味一锅星云",recipe:{"星砂":2,"雾盐":1}},
 "黄昏骰子":{chapter:3,icon:"🎲",note:"掷出的不是点数，而是一条路",recipe:{"记忆蜡":1,"铜齿轮":1,"星砂":1}}
});
const ITEMS=window.GAME_ITEMS;
const MATERIALS=window.GAME_MATERIALS;
const MATERIAL_GROUPS=window.MATERIAL_CATEGORIES;
const ENVIRONMENT=window.ENVIRONMENT_CONFIG;
const LEGACY_CUSTOMERS=[
 {name:"栗尾先生",group:"beast",kind:"兽客 · 狐狸",icon:"🦊",trait:"说话时总要先摸摸帽檐",item:"捕风瓶",story:"我替森林里的鸟儿保管歌声。昨晚有一支歌从盒中逃了出去，藏进了北风里。没有那支歌，知更鸟就等不到春天。",pay:{type:"coins",amount:7,item:null}},
 {name:"阿墨",group:"beast",kind:"兽客 · 乌鸦",icon:"🐦‍⬛",trait:"右眼戴着一枚黄铜单片镜",item:"不撒谎的镜子",story:"我的收藏里有三百七十二件闪亮的东西，却没有一件肯告诉我，我到底是不是一只好鸟。",pay:{type:"item",amount:3,item:"夜鸦羽毛"}},
 {name:"雨巷邮差",group:"night",kind:"夜行人",icon:"🧥",trait:"衣角一直滴着并不存在的雨",item:"雨天火柴",story:"有一封信在我的包里睡了二十年。收信人住在一条只会在雨夜出现的街上，我需要一点火光认路。",pay:{type:"coins",amount:10,item:null}},
 {name:"钟婆婆",group:"human",kind:"人类 · 钟表匠",icon:"👵",trait:"口袋里有许多细小的滴答声",item:"倒着走的怀表",story:"孙女第一次叫我奶奶的时候，我正忙着修钟，没来得及答应。只要一分钟，我想回去好好听一次。",pay:{type:"item",amount:4,item:"铜齿轮"}},
 {name:"瞌睡的獾",group:"beast",kind:"兽客 · 獾",icon:"🦡",trait:"每说三句话就打一个哈欠",item:"梦境纽扣",story:"我做了一个很长的梦，梦里花园永远是春天。最近梦的边缘开线了，你能帮我把它缝好吗？",pay:{type:"coins",amount:6,item:null}},
 {name:"没有影子的小姐",chapter:1,group:"night",kind:"身份不明",icon:"🎭",trait:"站在灯下，脚边仍空空如也",item:"影子雨伞",story:"我的影子离家出走了。它说除非我学会一个人散步，否则永远不回来。可街上的目光太亮了。",pay:{type:"item",amount:3,item:"月光碎片"}},
 {name:"贝壳里的男孩",chapter:2,group:"human",kind:"人类 · 来自海边",icon:"👦",trait:"耳边总有很远的潮声",item:"回声口琴",story:"奶奶临走前说了一句话，可浪太大，我没有听清。听说这种口琴能把错过的话再吹回来一次。",pay:{type:"item",amount:3,item:"回声贝壳"}},
 {name:"雾鹿女士",chapter:2,group:"beast",kind:"兽客 · 白鹿",icon:"🦌",trait:"鹿角之间浮着一小团晨雾",item:"雾路提灯",story:"我的鹿群误入了没有路标的白雾。它们都相信我认得归途，可其实我也已经迷路很久了。",pay:{type:"coins",amount:14,item:null}},
 {name:"失眠的云",chapter:2,group:"night",kind:"异客 · 云",icon:"☁️",trait:"说话时有细雨落在柜台上",item:"借梦枕",story:"城市里的梦太吵了，我已经三个月没有好好睡过。能不能借我一个安静得只剩风声的梦？",pay:{type:"item",amount:3,item:"雾盐"}},
 {name:"北斗船长",chapter:3,group:"human",kind:"人类 · 星海船长",icon:"🧑‍✈️",trait:"大衣上沾着几粒不会融化的星",item:"星图罗盘",story:"我的船从天空的裂缝掉了下来。船员还在星海上等我，我得在下一次月蚀前找到回去的方向。",pay:{type:"coins",amount:20,item:null}},
 {name:"衔火的蛾",chapter:3,group:"beast",kind:"兽客 · 月蛾",icon:"🦋",trait:"翅膀边缘闪着银蓝色火花",item:"记忆蜡烛",story:"我们一生只能看见一次真正的火。我想在生命结束以前，把那束光留给还没破茧的孩子。",pay:{type:"item",amount:3,item:"星砂"}},
 {name:"最后一颗星",chapter:3,group:"night",kind:"异客 · 星辰",icon:"⭐",trait:"它的声音像很远处的玻璃铃",item:"黎明信封",story:"天亮之后，人们就不会再记得我曾经来过。请替我把这封告别信寄给每一个曾在夜里许愿的人。",pay:{type:"item",amount:3,item:"记忆蜡"}}
];
const CUSTOMERS=window.GAME_VISITORS;
const VISIT_RULES=Object.fromEntries(CUSTOMERS.map(visitor=>[visitor.name,visitor.schedule]));
const CATEGORY_NAMES=window.VISITOR_CATEGORIES;
const VISITOR_MOODS=window.VISITOR_MOODS||{};
const DECOR=[
 {id:"lamp",name:"萤火吊灯",icon:"🏮",note:"用瓶中的萤火照亮柜台",comfort:2,effect:"夜行异客与星辰来访概率 +40%",attract:["night","astral"],power:2,cost:{coins:8}},
 {id:"plant",name:"会打哈欠的盆栽",icon:"🪴",note:"夜深时会自己缩进花盆",comfort:2,effect:"兽客与自然灵来访概率 +40%",attract:["beast","nature"],power:2,cost:{item:"月光碎片",amount:2}},
 {id:"rug",name:"星河地毯",icon:"✦",note:"织纹会随着夜色缓慢流动",comfort:3,effect:"吸引远方旅人，基础报酬 +1",attract:["traveler"],power:2,reward:1,cost:{coins:14}},
 {id:"cat",name:"看店黑猫",icon:"🐈‍⬛",note:"它自称不是店员，只是碰巧在此",comfort:4,effect:"兽客来访概率 +60%",attract:"beast",power:3,cost:{item:"夜鸦羽毛",amount:3}},
 {id:"clock",name:"十三点钟",icon:"🕰️",note:"每天会多敲一次不存在的钟声",comfort:5,effect:"人类来访概率 +60%",attract:"human",power:3,cost:{coins:24}},
 {id:"teaset",name:"雾气茶具",icon:"🍵",note:"总能倒出客人最怀念的味道",comfort:5,effect:"所有客人的基础报酬 +2",reward:2,cost:{item:"银线",amount:4}}
];
const DEFAULT_STATE={day:1,coins:12,inventory:{"月光碎片":2,"空玻璃瓶":1,"银线":2,"旧木片":2,"萤火粉":1,"铜齿轮":1,"夜鸦羽毛":1},history:[],relationships:{},decor:[],activeDecor:[],displayedProducts:[],discoveredItems:[],metCustomers:[],environmentDay:0,weather:null,dailyDrops:[],tomorrowForecast:null,resolved:false,closing:false,currentCustomer:1};
let state=load();
function clone(v){return JSON.parse(JSON.stringify(v))}
function load(){try{const old=JSON.parse(localStorage.getItem("late-lantern-save")||"null")||{},known=old.discoveredItems||Object.keys(old.inventory||{}).filter(n=>GAME_ITEMS[n]),met=old.metCustomers||Object.entries(old.relationships||{}).filter(([,r])=>r.visits>0).map(([name])=>name),decor=old.decor||[];return {...clone(DEFAULT_STATE),...old,inventory:{...DEFAULT_STATE.inventory,...(old.inventory||{})},relationships:old.relationships||{},decor,activeDecor:Array.isArray(old.activeDecor)?old.activeDecor.filter(id=>decor.includes(id)):[...decor],displayedProducts:(old.displayedProducts||[]).filter(name=>GAME_ITEMS[name]).slice(0,3),discoveredItems:known,metCustomers:met,dailyDrops:old.dailyDrops||[],closing:old.closing??!!old.resolved,currentCustomer:Number.isInteger(old.currentCustomer)?old.currentCustomer:(old.day||1)*5%CUSTOMERS.length}}catch{return clone(DEFAULT_STATE)}}
function save(){localStorage.setItem("late-lantern-save",JSON.stringify(state))}
function relation(name){if(!state.relationships[name])state.relationships[name]={favor:0,visits:0,deals:0};return state.relationships[name]}
function dailyCustomer(){return CUSTOMERS[state.currentCustomer]}
function calendar(day=state.day){const n=day-1,moonDay=n%28+1,month=Math.floor(n/28)%12+1,seasonIndex=Math.floor((month-1)/3),seasonKeys=["spring","summer","autumn","winter"],seasonNames=["春季","夏季","秋季","冬季"],phaseIndex=moonDay===1||moonDay===28?0:moonDay<=4?1:moonDay<=7?2:moonDay<=13?3:moonDay<=16?4:moonDay<=20?5:moonDay<=23?6:7,phaseIcons=["🌑","🌒","🌓","🌔","🌕","🌖","🌗","🌘"],phaseNames=["新月","娥眉月","上弦月","盈凸月","满月","亏凸月","下弦月","残月"],moonGroup=moonDay===1||moonDay===28?"new":moonDay>=14&&moonDay<=16?"full":moonDay<14?"waxing":"waning";return {weekday:n%7+1,moonDay,month,monthInSeason:(month-1)%3+1,season:seasonKeys[seasonIndex],seasonName:seasonNames[seasonIndex],year:Math.floor(n/336)+1,phaseIcon:phaseIcons[phaseIndex],phaseName:phaseNames[phaseIndex],moonGroup}}
function ruleMatches(rule,cal=calendar(),weatherId=state.weather?.id){return (!rule.weekday||rule.weekday.includes(cal.weekday))&&(!rule.season||rule.season.includes(cal.season))&&(!rule.month||rule.month.includes(cal.monthInSeason))&&(!rule.moon||rule.moon.includes(cal.moonGroup))&&(!rule.weather||rule.weather.includes(weatherId))}
function activeVisitRules(c){const favor=relation(c.name).favor;return (VISIT_RULES[c.name]||[{favor:0,label:"任何日子"}]).filter(r=>favor>=r.favor)}
function canVisitToday(c){return activeVisitRules(c).some(rule=>ruleMatches(rule))}
function chapterForDay(day){return [...CHAPTERS].reverse().find(c=>day>=c.start)}
function currentChapter(){return chapterForDay(state.day)}
function chapterNumber(){return currentChapter().id}
function chapterLabel(n){return ["零","一","二","三","四","五","六","七","八","九","十"][n]||String(n)}
function unlockedCustomers(){return CUSTOMERS.filter(c=>(c.chapter||1)<=chapterNumber())}
function ownedDecor(){return DECOR.filter(d=>state.decor.includes(d.id))}
function placedDecor(){return DECOR.filter(d=>state.activeDecor.includes(d.id))}
function shownProducts(){return state.displayedProducts.filter(name=>count(name)>0&&isDiscovered(name))}
function eligibleCustomersToday(){const eligible=unlockedCustomers().filter(canVisitToday);return eligible.length?eligible:unlockedCustomers()}
function visitorWeight(c){const favorBonus=Math.min(6,Math.floor(relation(c.name).favor/2)),decorBonus=Math.min(6,placedDecor().filter(d=>Array.isArray(d.attract)?d.attract.includes(c.category):d.attract===c.category).reduce((n,d)=>n+d.power,0));return 10+favorBonus+decorBonus}
function chooseCustomer(){const choices=eligibleCustomersToday().map(visitor=>({visitor,weight:visitorWeight(visitor)}));state.currentCustomer=CUSTOMERS.indexOf(weightedPick(choices).visitor)}
function count(name){return state.inventory[name]||0}
function isDiscovered(item){return state.discoveredItems.includes(item)}
function discoverCurrentRequest(){const item=dailyCustomer().item;if(!isDiscovered(item))state.discoveredItems.push(item)}
function markCurrentMet(){const name=dailyCustomer().name;if(!state.metCustomers.includes(name))state.metCustomers.push(name)}
function canCraft(item){return isDiscovered(item)&&Object.entries(ITEMS[item].recipe).every(([name,n])=>count(name)>=n)}
function weightedPick(list){let roll=Math.random()*list.reduce((n,x)=>n+x.weight,0);for(const entry of list){roll-=entry.weight;if(roll<=0)return entry}return list[list.length-1]}
function generateTomorrowForecast(day=state.day+1){const cal=calendar(day),pool=ENVIRONMENT.weather[cal.season].map(w=>clone(w)),count=Math.random()<.58?3:2,chosen=[];while(chosen.length<count&&pool.length){const picked=weightedPick(pool);chosen.push(picked);pool.splice(pool.indexOf(picked),1)}const total=chosen.reduce((n,w)=>n+w.weight,0);let assigned=0;return {day,options:chosen.map((w,i)=>{const probability=i===chosen.length-1?100-assigned:Math.round(w.weight/total*100);assigned+=probability;return {...w,probability}})}}
function generateWeather(cal=calendar()){const forecast=state.tomorrowForecast?.day===state.day?state.tomorrowForecast.options:null;return clone(weightedPick(forecast?.length?forecast:ENVIRONMENT.weather[cal.season]))}
function generateDrops(cal=calendar()){const candidates=new Map();for(const rule of ENVIRONMENT.drops){if(rule.season&&rule.season!==cal.season)continue;if(rule.weather&&rule.weather!==state.weather.id)continue;if(rule.moon&&rule.moon!==cal.moonGroup)continue;for(const name of rule.items)candidates.set(name,Math.max(candidates.get(name)||0,rule.chance))}const pool=[...candidates.entries()].map(([name,chance])=>({name,chance})),guaranteed=pool[Math.floor(Math.random()*pool.length)],picked=[guaranteed];for(const entry of pool){if(entry!==guaranteed&&picked.length<3&&Math.random()<entry.chance)picked.push(entry)}return picked.map(x=>({name:x.name,amount:1}))}
function ensureDailyEnvironment(){if(state.environmentDay===state.day&&state.weather&&state.dailyDrops.length){if(!state.tomorrowForecast||state.tomorrowForecast.day!==state.day+1)state.tomorrowForecast=generateTomorrowForecast();return}const cal=calendar();state.weather=generateWeather(cal);state.dailyDrops=generateDrops(cal);state.environmentDay=state.day;for(const drop of state.dailyDrops)state.inventory[drop.name]=(state.inventory[drop.name]||0)+drop.amount;state.tomorrowForecast=generateTomorrowForecast();state.history.unshift({day:state.day,story:`${state.weather.icon} ${state.weather.name}。清晨在店门口发现了${state.dailyDrops.map(d=>`${d.name}×${d.amount}`).join("、")}。`,outcome:"环境掉落"});save()}
function dailyMoodRoll(c){let hash=state.day*97;for(const char of c.name)hash=(hash*31+char.charCodeAt(0))%10007;return [-1,0,0,0,1][hash%5]}
function moodFor(c){const config=VISITOR_MOODS[c.name]||{},factors=[],weatherScore=config.weather?.[state.weather.id]||0;if(weatherScore)factors.push({score:weatherScore,label:`${weatherScore>0?"喜欢":"不喜欢"}${state.weather.name}`,icon:state.weather.icon});for(const d of placedDecor()){const score=config.decor?.[d.id]||0;if(score)factors.push({score,label:`${score>0?"喜欢":"不喜欢"}${d.name}`,icon:d.icon})}for(const name of shownProducts()){const score=config.products?.[name]||0;if(score)factors.push({score,label:`${score>0?"喜欢":"不喜欢"}展示的${name}`,icon:ITEMS[name].icon})}const favorScore=Math.min(3,Math.floor(relation(c.name).favor/3));if(favorScore)factors.push({score:favorScore,label:"信任这位店主",icon:"♥"});const random=dailyMoodRoll(c);if(random)factors.push({score:random,label:random>0?"今天心情不错":"今天有些心事",icon:random>0?"✦":"…"});return {score:Math.max(-5,Math.min(7,factors.reduce((n,f)=>n+f.score,0))),factors}}
function requestAmount(c){if(c.tradeStyle==="payment")return 1;const score=moodFor(c).score;return score>0?1:score<0?3:2}
function reward(c){const mood=moodFor(c),decorBonus=placedDecor().reduce((n,d)=>n+(d.reward||0),0),sensitivity=c.tradeStyle==="quantity"?0:c.tradeStyle==="both"?.5:1,moodBonus=c.pay.type==="coins"?Math.round(mood.score*2*sensitivity):Math.round(mood.score/2*sensitivity),bonus=c.pay.type==="coins"?decorBonus+moodBonus:Math.floor(decorBonus/2)+moodBonus;return {...c.pay,amount:Math.max(1,c.pay.amount+bonus)}}
function rewardLabel(c){const r=reward(c);return r.type==="coins"?`${r.amount} 枚铜币`:`${r.amount} × ${r.item}`}
function portraitMarkup(c){return c.portrait?`<img src="${c.portrait}" alt="" loading="lazy">`:c.icon}
function pageUnlocked(id){return chapterNumber()>=({shop:2,log:3,forecast:5}[id]||1)}
function showPage(id){if(!pageUnlocked(id))id="visitor";document.querySelectorAll(".game-page").forEach(p=>p.classList.toggle("active",p.id===`page-${id}`));document.querySelectorAll(".main-nav .nav-link").forEach(b=>b.classList.toggle("active",b.dataset.page===id));location.hash=id;scrollTo({top:0,behavior:"smooth"})}
function renderUnlocks(){document.querySelectorAll(".main-nav .nav-link").forEach(b=>{const unlocked=pageUnlocked(b.dataset.page);b.disabled=!unlocked;b.title=unlocked?"":`第 ${({shop:2,log:3,forecast:5}[b.dataset.page]||1)} 章解锁`});document.querySelector("#closingBar").hidden=!state.closing}
function renderWeatherEffect(cal){const layer=document.querySelector("#weatherLayer"),type=state.weather.id==="storm"&&cal.season==="winter"?"snow":state.weather.id;layer.dataset.weather=type;layer.dataset.season=cal.season;const amount={rain:52,snow:44,storm:46,clear:28,wind:22,fog:7}[type]||0;layer.innerHTML=Array.from({length:amount},(_,i)=>`<i style="--x:${(i*37+11)%101}%;--d:${(i%9)*-.31}s;--s:${.72+(i%7)*.13};--r:${(i*29)%80-40}px"></i>`).join("")+`<span class="weather-caption">${state.weather.icon} ${state.weather.name}</span>`}
function render(){
 const c=dailyCustomer(),rel=relation(c.name),needed=requestAmount(c),has=count(c.item)>=needed,craftable=canCraft(c.item),cal=calendar();
 const chapter=currentChapter(),next=CHAPTERS.find(x=>x.id===chapter.id+1),span=next?next.start-chapter.start:7,progress=next?Math.min(100,((state.day-chapter.start+1)/span)*100):100;
 document.querySelector("#chapterBadge").textContent=`第${chapterLabel(chapter.id)}章`;document.querySelector("#chapterName").textContent=`第${chapterLabel(chapter.id)}章 · ${chapter.name}`;document.querySelector("#chapterHint").textContent=next?`距离「${next.name}」还有 ${next.start-state.day} 天`:"年度故事已经写完 · 小店仍会逐日营业";document.querySelector("#chapterProgress").style.width=`${progress}%`;renderWeatherEffect(cal);renderUnlocks();
 document.querySelector("#dayNumber").textContent=state.day;document.querySelector("#coinCount").textContent=state.coins;document.querySelector(".moon").textContent=cal.phaseIcon;document.querySelector("#calendarMoon").textContent=cal.phaseIcon;document.querySelector("#moonName").textContent=`${cal.phaseName} · 第 ${cal.moonDay} 夜`;document.querySelector("#seasonIcon").textContent={spring:"🌱",summer:"☀",autumn:"🍂",winter:"❄"}[cal.season];document.querySelector("#seasonName").textContent=cal.seasonName;document.querySelector("#monthName").textContent=`${cal.seasonName[0]}${["一","二","三"][cal.monthInSeason-1]}月`;document.querySelector("#weekdayName").textContent=`星期${["一","二","三","四","五","六","日"][cal.weekday-1]}`;document.querySelector("#weatherIcon").textContent=state.weather.icon;document.querySelector("#weatherName").textContent=state.weather.name;document.querySelector("#calendarRibbon").dataset.season=cal.season;document.querySelector("#calendarRibbon").dataset.weather=state.weather.id;document.querySelector("#calendarDate").textContent=`第 ${cal.year} 年 · 第 ${cal.month} 月`;document.querySelector("#dailyDropList").innerHTML=state.dailyDrops.map((d,i)=>`<span style="--i:${i}"><b>${MATERIALS[d.name].icon}</b>${d.name}<small>+${d.amount}</small></span>`).join("");document.querySelector("#windowMoon").textContent=cal.phaseIcon;document.querySelector("#windowSky").textContent=`${cal.seasonName} · ${cal.phaseName} · ${state.weather.name}`;document.querySelector("#room").dataset.season=cal.season;
 document.querySelector("#portraitImage").src=c.portrait;document.querySelector("#portraitImage").alt=c.name;document.querySelector("#customerKind").textContent=c.kind;document.querySelector("#customerName").textContent=c.name;document.querySelector("#customerTrait").textContent=c.trait;document.querySelector("#customerStory").textContent=c.story;document.querySelector("#requestedItem").textContent=`${c.item} × ${needed}`;document.querySelector("#paymentOffer").textContent=rewardLabel(c);document.querySelector("#currentFavor").textContent=rel.favor;document.querySelector("#favorHearts").innerHTML=Array.from({length:5},(_,i)=>`<i class="${rel.favor>=i*2+2?"full":rel.favor===i*2+1?"half":"empty"}"></i>`).join("");
 document.querySelector("#availabilityText").textContent=has?`库存足够 · 拥有 ${count(c.item)} / 需要 ${needed}`:craftable?`还差 ${needed-count(c.item)} 件，可以继续制作`:`库存 ${count(c.item)} / ${needed}，材料也不足`;document.querySelector(".dot").style.background=has?"#64715d":craftable?"#c79346":"#a5402d";document.querySelector("#sellButton").disabled=!has||state.resolved;document.querySelector("#craftButton").disabled=!craftable||has||state.resolved;document.querySelector("#refuseButton").disabled=state.resolved;document.querySelector("#craftCost").innerHTML=`<small>${Object.entries(ITEMS[c.item].recipe).map(([n,q])=>`${n}×${q}`).join(" · ")}</small>`;
 renderMood(c);renderForecast();renderTomorrowForecast();renderInventory();renderQuickInventory();renderRelationships();renderHistory();renderLog();renderShop();save();
}
function renderMood(c){const mood=moodFor(c),tone=mood.score>=3?"delighted":mood.score>0?"pleased":mood.score<0?"upset":"neutral",condition=mood.score>0?"交易条件对你更有利":mood.score<0?"交易条件对你更不利":"交易条件没有变化",styleLabel={payment:"影响付款",quantity:"影响需求数量",both:"同时影响需求与付款"}[c.tradeStyle],titles={delighted:`心情很好 · ${condition}`,pleased:`有些满意 · ${condition}`,neutral:`心情平静 · ${condition}`,upset:`有些不悦 · ${condition}`};document.querySelector("#moodTitle").textContent=titles[tone];document.querySelector(".mood-panel").dataset.tone=tone;const detail=chapterNumber()<8?`<span class="mood-chip neutral locked-mood"><b>?</b>第八章后才能读懂原因</span>`:mood.factors.length?mood.factors.map(f=>`<span class="mood-chip ${f.score>0?"positive":"negative"}"><b>${f.icon}</b>${f.label}<em>${f.score>0?"+":""}${f.score}</em></span>`).join(""):`<span class="mood-chip neutral"><b>☾</b>没有特别在意的事<em>0</em></span>`;document.querySelector("#moodEffects").innerHTML=`<span class="mood-chip trade-style"><b>⌁</b>${styleLabel}</span>${detail}`}
function renderForecast(){const chosen=dailyCustomer(),pool=eligibleCustomersToday(),candidates=pool.some(c=>c.name===chosen.name)?pool:[chosen,...pool],total=candidates.reduce((n,c)=>n+visitorWeight(c),0);document.querySelector("#forecastCount").textContent=`${candidates.length} 位符合条件 · 按权重随机来一位`;document.querySelector("#potentialVisitors").innerHTML=candidates.map((c,i)=>{const selected=c.name===chosen.name,met=state.metCustomers.includes(c.name),chance=Math.round(visitorWeight(c)/total*100);return `<article class="forecast-person ${selected?"selected":"not-selected"}" style="--i:${i}"><span class="forecast-avatar">${met?portraitMarkup(c):"?"}</span><div><small>${selected?"今晚来访":"今夜未出现"}</small><strong>${met?c.name:"未知的客人"}</strong><em>${met?CATEGORY_NAMES[c.category]:"尚未结识"} · 约 ${chance}%</em></div>${selected?"<i>✓</i>":""}</article>`}).join("")}
function preferenceHints(c){const mood=VISITOR_MOODS[c.name]||{},weatherNames={clear:"晴天",rain:"雨天",fog:"雾天",wind:"有风",storm:"风雪与雷暴"},hints=[];for(const [id,score] of Object.entries(mood.weather||{}))hints.push(`${score>0?"喜欢":"不喜欢"}${weatherNames[id]}`);for(const [id,score] of Object.entries(mood.decor||{})){const d=DECOR.find(x=>x.id===id);if(d)hints.push(`${score>0?"喜欢":"不喜欢"}${d.name}`)}for(const [name,score] of Object.entries(mood.products||{}))hints.push(`${score>0?"喜欢":"不喜欢"}${name}`);return hints.slice(0,3)}
function renderTomorrowForecast(){const forecast=state.tomorrowForecast||generateTomorrowForecast(),day=forecast.day,cal=calendar(day),weekday=["一","二","三","四","五","六","日"][cal.weekday-1];document.querySelector("#tomorrowCalendar").innerHTML=`<div><small>明日</small><strong>第 ${day} 日</strong></div><div><small>星期</small><strong>星期${weekday}</strong></div><div><small>季节与月份</small><strong>${cal.seasonName} · ${cal.seasonName[0]}${["一","二","三"][cal.monthInSeason-1]}月</strong></div><div><small>月相</small><strong>${cal.phaseIcon} ${cal.phaseName}</strong></div>`;document.querySelector("#weatherOptions").innerHTML=forecast.options.map((w,i)=>`<article style="--i:${i}"><span>${w.icon}</span><div><small>可能天气</small><strong>${w.name}</strong><i><b style="width:${w.probability}%"></b></i></div><em>${w.probability}%</em></article>`).join("");const guestSection=document.querySelector("#forecastGuests");if(chapterNumber()<7){guestSection.innerHTML=`<div class="forecast-locked"><b>第七章解锁</b><span>继续经营后，风向针会开始提示明日可能来访的客人。</span></div>`;return}const weatherIds=forecast.options.map(w=>w.id),chapter=chapterForDay(day).id,pool=CUSTOMERS.filter(c=>(c.chapter||1)<=chapter&&activeVisitRules(c).some(rule=>weatherIds.some(id=>ruleMatches(rule,cal,id))));guestSection.innerHTML=`<div class="section-heading"><div><p class="eyebrow">明日门铃</p><h2>可能来访的客人</h2></div><span class="catalog-note">天气尚未确定，名单可能较长</span></div><div class="tomorrow-guests">${pool.map(c=>{const met=state.metCustomers.includes(c.name),hints=chapterNumber()>=8&&met?preferenceHints(c):[];return `<article class="tomorrow-guest ${met?"known":"unknown"}"><span>${met?portraitMarkup(c):"?"}</span><div><small>${met?CATEGORY_NAMES[c.category]:"尚未结识"}</small><strong>${met?c.name:"未知的客人"}</strong>${chapterNumber()<8?`<em>第八章解锁喜好</em>`:hints.length?`<p>${hints.map(h=>`<i>${h}</i>`).join("")}</p>`:""}</div></article>`}).join("")||`<p class="log-empty">风向针没有捕捉到清晰的脚步声。</p>`}</div>`}
function canArrangeProducts(){return chapterNumber()>=6&&state.closing}
function inventoryCard(name,d,isProduct=false){const q=count(name),shown=shownProducts().includes(name),full=shownProducts().length>=3,canArrange=canArrangeProducts(),canShelfCraft=chapterNumber()>=4&&state.closing&&canCraft(name);return `<article class="item ${q?"":"empty"} ${shown?"displayed":""}"><span class="item-count">${q}</span><span class="item-icon">${d.icon}</span><span class="item-name">${name}</span><span class="item-note">${d.note}</span>${isProduct?`<div class="item-actions"><button class="display-toggle shelf-craft" data-shelf-craft="${name}" ${canShelfCraft?"":"disabled"}>${chapterNumber()<4?"第四章解锁制作":!state.closing?"打烊后制作":canCraft(name)?"制作一件":"材料不足"}</button><button class="display-toggle" data-display="${name}" ${!canArrange||(!shown&&(q<1||full))?"disabled":""}>${chapterNumber()<6?"第六章解锁展示":!state.closing?"接待中锁定":shown?"收起展示":"摆到柜台"}</button></div>`:""}</article>`}
function renderInventory(){state.displayedProducts=shownProducts();const products=Object.entries(ITEMS).filter(([name])=>isDiscovered(name)),shown=shownProducts(),canArrange=canArrangeProducts(),shelf=document.querySelector("#displayShelf");shelf.classList.toggle("locked",!canArrange);document.querySelector("#displayShelfHint").textContent=chapterNumber()<6?"第六章解锁成品展示":state.closing?"正在为明日布置 · 调整会影响明天":"客人仍在店里 · 今晚打烊后才能调整";document.querySelector("#displayedProducts").innerHTML=shown.length?shown.map(name=>`<span><b>${ITEMS[name].icon}</b>${name}<button data-display="${name}" aria-label="收起${name}" ${canArrange?"":"disabled"}>×</button></span>`).join("")+`<small>${shown.length} / 3</small>`:`<em>尚未展示任何成品 · 0 / 3</em>`;const productSection=`<section class="inventory-group products"><header><div><p class="eyebrow">FINISHED GOODS</p><h2>已发现的奇异商品</h2></div><span>${products.length} / ${Object.keys(ITEMS).length} 种配方已发现</span></header><div class="inventory-grid-inner">${products.map(([n,d])=>inventoryCard(n,d,true)).join("")}</div></section>`;const materialSections=Object.entries(MATERIAL_GROUPS).map(([key,group])=>{const entries=Object.entries(MATERIALS).filter(([,d])=>d.category===key);return `<section class="inventory-group" style="--group-color:${group.color}"><header><div><p class="eyebrow">${key.toUpperCase()}</p><h2>${group.name}</h2></div><span>${group.note}</span></header><div class="inventory-grid-inner">${entries.map(([n,d])=>inventoryCard(n,d)).join("")}</div></section>`}).join("");document.querySelector("#inventoryGrid").innerHTML=productSection+materialSections;document.querySelectorAll("[data-display]").forEach(b=>b.addEventListener("click",()=>toggleProductDisplay(b.dataset.display)));document.querySelectorAll("[data-shelf-craft]").forEach(b=>b.addEventListener("click",()=>craftFromShelf(b.dataset.shelfCraft)))}
function toggleProductDisplay(name){if(!canArrangeProducts())return;const shown=state.displayedProducts.includes(name);if(shown)state.displayedProducts=state.displayedProducts.filter(n=>n!==name);else if(count(name)>0&&state.displayedProducts.length<3)state.displayedProducts.push(name);save();render()}
function craftFromShelf(name){if(chapterNumber()<4||!state.closing||!canCraft(name))return;for(const [material,amount] of Object.entries(ITEMS[name].recipe))state.inventory[material]-=amount;state.inventory[name]=(state.inventory[name]||0)+1;save();render();pulseClass(`[data-shelf-craft="${name}"]`,"crafted-button",650)}
function renderQuickInventory(){const entries=[...Object.entries(ITEMS).filter(([n])=>isDiscovered(n)),...Object.entries(MATERIALS)].filter(([n])=>count(n)>0),total=entries.reduce((n,[name])=>n+count(name),0);document.querySelector("#quickInventoryCount").textContent=`${total} 件库存`;document.querySelector("#quickInventory").innerHTML=entries.length?`<div class="quick-grid">${entries.map(([name,d])=>`<span class="quick-item"><b>${d.icon}</b><em>${name}</em><small>×${count(name)}</small></span>`).join("")}</div><button class="text-button quick-more" data-page="inventory">查看完整货架 →</button>`:`<p class="quick-empty">货架上暂时空空如也。</p>`;document.querySelector("#quickInventory [data-page]")?.addEventListener("click",()=>showPage("inventory"))}
function scheduleIntel(c,favor){const chips=[],base=(VISIT_RULES[c.name]||[]).filter(rule=>(rule.favor||0)===0),seasons={spring:"春季",summer:"夏季",autumn:"秋季",winter:"冬季"},weather={clear:"晴天",rain:"雨天",fog:"雾天",wind:"有风",storm:"雷暴或风雪"},moons={new:"新月",waxing:"盈月",full:"满月",waning:"亏月"},weekdays=["一","二","三","四","五","六","日"];if(favor>=1){const before=chips.length;for(const rule of base){if(rule.season)chips.push(`季节：${rule.season.map(x=>seasons[x]).join("、")}`);if(rule.month)chips.push(`月份：每季第${rule.month.join("、")}月`)}if(chips.length===before)chips.push("季节：没有固定季节") }if(favor>=2){const before=chips.length;for(const rule of base)if(rule.weekday)chips.push(`星期：${rule.weekday.map(x=>"周"+weekdays[x-1]).join("、")}`);if(chips.length===before)chips.push("星期：没有固定星期") }if(favor>=3){const before=chips.length;for(const rule of base){if(rule.weather)chips.push(`天气：${rule.weather.map(x=>weather[x]).join("、")}`);if(rule.moon)chips.push(`月相：${rule.moon.map(x=>moons[x]).join("、")}`)}if(chips.length===before)chips.push("环境：没有固定天气或月相") }if(favor>=4){const before=chips.length;for(const rule of (VISIT_RULES[c.name]||[]).filter(rule=>(rule.favor||0)>0))chips.push(`追加：${rule.label}`);if(chips.length===before)chips.push("追加：暂时没有新的来访窗口") }return [...new Set(chips)]}
function visitorRarity(c){return c.chapter>=3?"稀有":c.chapter===2?"少见":"常见"}
function preferenceLabels(c,positive=true){const config=VISITOR_MOODS[c.name]||{},sign=positive?1:-1,labels=[],weather={clear:"晴天",rain:"雨天",fog:"雾天",wind:"有风",storm:"雷暴或风雪"};for(const [id,score] of Object.entries(config.weather||{}))if(Math.sign(score)===sign)labels.push(`天气 · ${weather[id]}`);for(const [id,score] of Object.entries(config.decor||{})){const d=DECOR.find(x=>x.id===id);if(d&&Math.sign(score)===sign)labels.push(`${d.icon} ${d.name}`)}for(const [name,score] of Object.entries(config.products||{}))if(Math.sign(score)===sign)labels.push(`${ITEMS[name].icon} ${name}`);return labels}
function relationshipCard(c){const locked=c.chapter>chapterNumber(),r=relation(c.name),met=state.metCustomers.includes(c.name),level=r.favor>=8?"知己":r.favor>=4?"熟客":r.favor?"相识":"初见";if(locked)return `<article class="relation-card locked"><span class="relation-icon">⌛</span><div><span class="tag">第 ${c.chapter} 章解锁</span><h3>尚未写下的名字</h3><p>迟灯巷的雾还没有散到那里。</p></div></article>`;if(!met)return `<article class="relation-card unknown"><span class="relation-icon">?</span><div><span class="tag">${CATEGORY_NAMES[c.category]}</span><h3>尚未到访的客人</h3><p>第一次见面后，来访规律会记录在这里。</p></div></article>`;const intel=scheduleIntel(c,r.favor),likes=r.favor>=6?preferenceLabels(c,true):[],dislikes=r.favor>=7?preferenceLabels(c,false):[],pips=Array.from({length:10},(_,i)=>`<i class="${i<r.favor?"earned":""}">${i+1}</i>`).join("");return `<article class="relation-card ${r.favor>=8?"bonded":""}"><span class="relation-icon">${portraitMarkup(c)}</span><div><span class="tag">${c.kind}</span><h3>${c.name}</h3><p>${level} · 完成来访 ${r.visits} 次 · 成交 ${r.deals} 次</p><div class="relationship-levels" aria-label="好感 ${r.favor}/10">${pips}</div><div class="visit-schedule">${intel.length?intel.map(text=>`<span class="schedule-chip active">◉ ${text}</span>`).join(""):`<span class="schedule-chip locked-rule">好感 1 后开始读懂来访规律</span>`}</div>${r.favor>=5?`<div class="visitor-rarity rarity-${c.chapter}">✦ 稀有度 · ${visitorRarity(c)}</div>`:""}${r.favor>=6?`<div class="preference-row likes"><b>喜欢</b>${likes.map(x=>`<span>${x}</span>`).join("")}</div>`:""}${r.favor>=7?`<div class="preference-row dislikes"><b>不喜欢</b>${dislikes.map(x=>`<span>${x}</span>`).join("")}</div>`:""}${r.favor>=8?`<div class="bond-highlight"><b>✦ 关系高光</b><span>这位客人已经把迟灯杂货铺当作熟悉的归处。</span></div>`:""}${r.favor>=9?`<div class="future-status">◇ 可雇佣 <small>功能规划中</small></div>`:""}${r.favor>=10?`<div class="max-bond">♥ 羁绊已满</div>`:""}<div class="favor-bar"><i style="width:${Math.min(100,r.favor*10)}%"></i></div><small>当前好感 ${r.favor}/10</small></div></article>`}
function renderRelationships(){document.querySelector("#relationshipGrid").innerHTML=Object.entries(CATEGORY_NAMES).map(([key,label])=>{const visitors=CUSTOMERS.filter(c=>c.category===key),known=visitors.filter(c=>state.metCustomers.includes(c.name)).length;return `<section class="visitor-group"><header><div class="visitor-title"><span class="category-emblem category-${key}" aria-hidden="true"></span><div><p class="eyebrow">${key.toUpperCase()}</p><h2>${label}</h2></div></div><span>${known} / ${visitors.length} 已结识</span></header><div class="relationship-grid-inner">${visitors.map(relationshipCard).join("")}</div></section>`}).join("")}
function renderHistory(){document.querySelector("#historyList").innerHTML=state.history.length?state.history.map(h=>`<div class="history-row"><span class="history-day">第 ${h.day} 日</span><span>${h.story}</span><span class="history-outcome">${h.outcome}</span></div>`).join(""):`<div class="history-row"><span class="history-day">开店前</span><span>你擦亮门上的铜铃，等待第一个故事。</span><span class="history-outcome">尚无记录</span></div>`}
function renderLog(){const met=CUSTOMERS.filter(c=>state.metCustomers.includes(c.name)),appearances=c=>relation(c.name).visits+(!state.resolved&&dailyCustomer().name===c.name?1:0),totals=met.reduce((sum,c)=>{const r=relation(c.name);sum.visits+=appearances(c);sum.deals+=r.deals;sum.favor+=r.favor;return sum},{visits:0,deals:0,favor:0}),rate=totals.visits?Math.round(totals.deals/totals.visits*100):0,avg=met.length?(totals.favor/met.length).toFixed(1):"0.0";document.querySelector("#logSummary").innerHTML=`<article><span>📅</span><small>开店时间</small><strong>第 ${state.day} 天</strong><em>走过 ${calendar().month} 个月份</em></article><article><span>🔔</span><small>来客记录</small><strong>${totals.visits} 次</strong><em>结识 ${met.length} / ${CUSTOMERS.length} 位客人</em></article><article><span>🤝</span><small>成功交易</small><strong>${totals.deals} 次</strong><em>成交率 ${rate}%</em></article><article><span>♥</span><small>平均好感</small><strong>${avg}</strong><em>当前共有 ${totals.favor} 点好感</em></article>`;document.querySelector("#guestStats").innerHTML=met.length?met.map(c=>{const r=relation(c.name),visits=appearances(c),success=visits?Math.round(r.deals/visits*100):0;return `<article class="guest-stat"><span class="guest-stat-icon">${portraitMarkup(c)}</span><div><small>${CATEGORY_NAMES[c.category]}</small><strong>${c.name}</strong><em>${c.kind}</em></div><dl><div><dt>出现</dt><dd>${visits}</dd></div><div><dt>成交</dt><dd>${r.deals}</dd></div><div><dt>成功率</dt><dd>${success}%</dd></div><div><dt>好感</dt><dd>${r.favor}/10</dd></div></dl></article>`}).join(""):`<p class="log-empty">门铃还没有留下第一位客人的名字。</p>`}
function costLabel(d){return d.cost.coins?`${d.cost.coins} 枚铜币`:`${d.cost.amount} × ${d.cost.item}`}
function canBuy(d){return d.cost.coins?state.coins>=d.cost.coins:count(d.cost.item)>=d.cost.amount}
function decorScene(d){const scenes={lamp:`<b>${d.icon}</b><i class="lamp-glow"></i>`,plant:`<b>${d.icon}</b><i class="plant-yawn">呼…</i>`,rug:`<i class="rug-star">✦</i><i class="rug-star">·</i><i class="rug-star">✧</i>`,cat:`<b>${d.icon}</b><i class="cat-thought">♪</i>`,clock:`<b>${d.icon}</b><i class="clock-pendulum"></i>`,teaset:`<b>${d.icon}</b><i class="steam steam-one">〰</i><i class="steam steam-two">〰</i>`};return scenes[d.id]||d.icon}
function renderShop(){const owned=ownedDecor(),active=placedDecor(),canArrange=state.closing;document.querySelector("#comfortScore").textContent=active.reduce((n,d)=>n+d.comfort,0);document.querySelector("#decorStatus").textContent=`随时可以购买 · ${canArrange?"正在打烊布置":"客人离开后才能摆放"} · 已拥有 ${owned.length} 件`;document.querySelector("#decorLayer").innerHTML=active.map(d=>`<span class="placed-decor decor-${d.id}" title="${d.name}">${decorScene(d)}</span>`).join("");document.querySelector("#decorGrid").innerHTML=DECOR.map(d=>{const bought=state.decor.includes(d.id),placed=state.activeDecor.includes(d.id);return `<article class="decor-card ${bought?"owned":""} ${placed?"is-placed":""}"><span class="decor-icon">${d.icon}</span><div><h3>${d.name}</h3><p>${d.note}</p><div class="effect-tag">✦ ${d.effect}</div><small>${placed?"正在店内生效":bought?"已拥有 · 尚未摆出":"温暖度 +"+d.comfort}</small></div>${bought?`<button class="button ${placed?"primary":"ghost"}" data-decor-toggle="${d.id}" ${canArrange?"":"disabled"}>${canArrange?(placed?"收起来":"摆出来"):"打烊后布置"}</button>`:`<button class="button primary" data-buy="${d.id}" ${!canBuy(d)?"disabled":""}>${costLabel(d)}</button>`}</article>`}).join("");document.querySelectorAll("[data-buy]").forEach(b=>b.addEventListener("click",()=>buyDecor(b.dataset.buy)));document.querySelectorAll("[data-decor-toggle]").forEach(b=>b.addEventListener("click",()=>toggleDecor(b.dataset.decorToggle)))}
function toggleDecor(id){if(!state.closing||!state.decor.includes(id))return;state.activeDecor=state.activeDecor.includes(id)?state.activeDecor.filter(x=>x!==id):[...state.activeDecor,id];save();render()}
function buyDecor(id){const d=DECOR.find(x=>x.id===id);if(!d||state.decor.includes(id)||!canBuy(d))return;if(d.cost.coins)state.coins-=d.cost.coins;else state.inventory[d.cost.item]-=d.cost.amount;state.decor.push(id);if(state.closing)state.activeDecor.push(id);save();render();document.querySelector("#noticeLabel").textContent="店铺陈设";document.querySelector("#noticeTitle").textContent=`添置了${d.name}`;document.querySelector("#noticeText").textContent=state.closing?`${d.note}。它已经摆进店里，将从明天开始影响客人。`:`${d.note}。物件已经买下，今晚客人离开后就可以把它摆进店里。`;document.querySelector("#noticeDialog").showModal()}
function pulseClass(selector,className,duration=700){const el=document.querySelector(selector);if(!el)return;el.classList.remove(className);void el.offsetWidth;el.classList.add(className);setTimeout(()=>el.classList.remove(className),duration)}
function playDayIntro(){const page=document.querySelector("#page-visitor");page.classList.remove("is-revealing");void page.offsetWidth;page.classList.add("is-revealing");setTimeout(()=>page.classList.remove("is-revealing"),1800)}
function complete(action){const c=dailyCustomer(),rel=relation(c.name);let title,text,label,icon="✦",outcome;if(action==="craft"){for(const [n,q] of Object.entries(ITEMS[c.item].recipe))state.inventory[n]-=q;state.inventory[c.item]=(state.inventory[c.item]||0)+1;save();render();document.querySelector("#availabilityText").textContent="制作完成，继续检查客人的需求数量";pulseClass("#page-visitor","crafting",850);return}rel.visits+=1;if(action==="sell"){const r=reward(c),needed=requestAmount(c);state.inventory[c.item]-=needed;if(state.inventory[c.item]<1)state.displayedProducts=state.displayedProducts.filter(name=>name!==c.item);if(r.type==="coins")state.coins+=r.amount;else state.inventory[r.item]=(state.inventory[r.item]||0)+r.amount;rel.favor=Math.min(10,rel.favor+2);rel.deals+=1;title="门铃轻轻响了两次";text=`${c.name}带着 ${needed} 件${c.item}离开了。最终支付了${r.type==="coins"?r.amount+" 枚铜币":r.amount+" × "+r.item}，你们的好感增加了 2 点。`;outcome=`售出「${c.item}」×${needed} · 好感 +2`;label="交易完成"}else{rel.favor=Math.max(0,rel.favor-1);title="有些故事不属于今晚";text=`你向${c.name}摇了摇头。客人把故事重新收好，消失在门外的夜色里。`;outcome="婉言拒绝 · 好感 -1";icon="☾";label="客人离开了"}state.resolved=true;state.closing=true;state.history.unshift({day:state.day,story:`${c.name}来寻找${c.item}。`,outcome});save();render();pulseClass("#page-visitor",action==="sell"?"sale-complete":"guest-leaving",800);showDialog(icon,label,title,text)}
function showDialog(icon,label,title,text){document.querySelector("#dialogIcon").textContent=icon;document.querySelector("#dialogLabel").textContent=label;document.querySelector("#dialogTitle").textContent=title;document.querySelector("#dialogText").textContent=text;document.querySelector("#resultDialog").showModal()}
function beginClosing(){document.querySelector("#resultDialog").close()}
function nextDay(){if(!state.closing)return;const oldChapter=chapterNumber();state.day+=1;state.resolved=false;state.closing=false;ensureDailyEnvironment();const newChapter=chapterNumber();chooseCustomer();markCurrentMet();discoverCurrentRequest();if(newChapter>oldChapter){const chapter=currentChapter();state.history.unshift({day:state.day,story:`迟灯巷深处传来陌生的门铃声。`,outcome:`解锁第${chapterLabel(newChapter)}章「${chapter.name}」`})}save();render();showPage("visitor");playDayIntro();if(newChapter>oldChapter){const chapter=currentChapter();document.querySelector("#noticeLabel").textContent="新章节解锁";document.querySelector("#noticeTitle").textContent=`第${chapterLabel(newChapter)}章 · ${chapter.name}`;document.querySelector("#noticeText").textContent=`${chapter.note}。新的店铺能力已经苏醒。`;document.querySelector("#noticeDialog").showModal()}}
document.querySelectorAll(".nav-link").forEach(b=>b.addEventListener("click",()=>showPage(b.dataset.page)));document.querySelector("#sellButton").addEventListener("click",()=>complete("sell"));document.querySelector("#craftButton").addEventListener("click",()=>complete("craft"));document.querySelector("#refuseButton").addEventListener("click",()=>complete("refuse"));document.querySelector("#nextDayButton").addEventListener("click",beginClosing);document.querySelector("#endDayButton").addEventListener("click",nextDay);document.querySelector("#noticeClose").addEventListener("click",()=>document.querySelector("#noticeDialog").close());document.querySelector("#resetButton").addEventListener("click",()=>{if(confirm("⚠️ 确定要清空本地数据吗？\n\n所有天数、物品、铜币、访客关系、经营日志和已购买陈设都会永久删除，且无法恢复。")){state=clone(DEFAULT_STATE);ensureDailyEnvironment();markCurrentMet();discoverCurrentRequest();save();render();showPage("visitor");alert("本地数据已经清空。迟灯杂货铺重新开张了。")}});
ensureDailyEnvironment();markCurrentMet();discoverCurrentRequest();render();showPage(["visitor","inventory","ledger","shop","forecast","log"].includes(location.hash.slice(1))?location.hash.slice(1):"visitor");if(!location.hash||location.hash==="#visitor")setTimeout(playDayIntro,80);
