const ITEMS={"捕风瓶":{icon:"🏺",note:"瓶口偶尔传来口哨声",recipe:{"月光碎片":1,"空玻璃瓶":1}},"不撒谎的镜子":{icon:"🪞",note:"照见的未必是脸",recipe:{"银线":2,"月光碎片":1}},"雨天火柴":{icon:"🔥",note:"只能在雨里点燃",recipe:{"旧木片":1,"萤火粉":1}},"倒着走的怀表":{icon:"🕰️",note:"能借回短短一分钟",recipe:{"铜齿轮":2,"银线":1}},"梦境纽扣":{icon:"🔘",note:"缝住一个快醒的梦",recipe:{"银线":1,"萤火粉":1}},"影子雨伞":{icon:"☂️",note:"遮住不愿被看见的人",recipe:{"夜鸦羽毛":2,"旧木片":1}}};
const MATERIALS={"月光碎片":{icon:"🌙",note:"薄而冷的微光"},"空玻璃瓶":{icon:"🫙",note:"里面什么也没有，大概"},"银线":{icon:"🧵",note:"比头发更细"},"旧木片":{icon:"🪵",note:"来自一扇旧门"},"萤火粉":{icon:"✨",note:"轻轻发着绿光"},"铜齿轮":{icon:"⚙️",note:"仍在缓慢转动"},"夜鸦羽毛":{icon:"🪶",note:"摸起来像一片夜色"}};
const CUSTOMERS=[
 {name:"栗尾先生",group:"beast",kind:"兽客 · 狐狸",icon:"🦊",trait:"说话时总要先摸摸帽檐",item:"捕风瓶",story:"我替森林里的鸟儿保管歌声。昨晚有一支歌从盒中逃了出去，藏进了北风里。没有那支歌，知更鸟就等不到春天。",pay:{type:"coins",amount:7,item:null}},
 {name:"阿墨",group:"beast",kind:"兽客 · 乌鸦",icon:"🐦‍⬛",trait:"右眼戴着一枚黄铜单片镜",item:"不撒谎的镜子",story:"我的收藏里有三百七十二件闪亮的东西，却没有一件肯告诉我，我到底是不是一只好鸟。",pay:{type:"item",amount:3,item:"夜鸦羽毛"}},
 {name:"雨巷邮差",group:"night",kind:"夜行人",icon:"🧥",trait:"衣角一直滴着并不存在的雨",item:"雨天火柴",story:"有一封信在我的包里睡了二十年。收信人住在一条只会在雨夜出现的街上，我需要一点火光认路。",pay:{type:"coins",amount:10,item:null}},
 {name:"钟婆婆",group:"human",kind:"人类 · 钟表匠",icon:"👵",trait:"口袋里有许多细小的滴答声",item:"倒着走的怀表",story:"孙女第一次叫我奶奶的时候，我正忙着修钟，没来得及答应。只要一分钟，我想回去好好听一次。",pay:{type:"item",amount:4,item:"铜齿轮"}},
 {name:"瞌睡的獾",group:"beast",kind:"兽客 · 獾",icon:"🦡",trait:"每说三句话就打一个哈欠",item:"梦境纽扣",story:"我做了一个很长的梦，梦里花园永远是春天。最近梦的边缘开线了，你能帮我把它缝好吗？",pay:{type:"coins",amount:6,item:null}},
 {name:"没有影子的小姐",group:"night",kind:"身份不明",icon:"🎭",trait:"站在灯下，脚边仍空空如也",item:"影子雨伞",story:"我的影子离家出走了。它说除非我学会一个人散步，否则永远不回来。可街上的目光太亮了。",pay:{type:"item",amount:3,item:"月光碎片"}}
];
const DECOR=[
 {id:"lamp",name:"萤火吊灯",icon:"🏮",note:"用瓶中的萤火照亮柜台",comfort:2,effect:"夜行人来访概率 +40%",attract:"night",power:2,cost:{coins:8}},
 {id:"plant",name:"会打哈欠的盆栽",icon:"🪴",note:"夜深时会自己缩进花盆",comfort:2,effect:"兽客来访概率 +40%",attract:"beast",power:2,cost:{item:"月光碎片",amount:2}},
 {id:"rug",name:"星河地毯",icon:"✦",note:"织纹会随着夜色缓慢流动",comfort:3,effect:"所有客人的基础报酬 +1",reward:1,cost:{coins:14}},
 {id:"cat",name:"看店黑猫",icon:"🐈‍⬛",note:"它自称不是店员，只是碰巧在此",comfort:4,effect:"兽客来访概率 +60%",attract:"beast",power:3,cost:{item:"夜鸦羽毛",amount:3}},
 {id:"clock",name:"十三点钟",icon:"🕰️",note:"每天会多敲一次不存在的钟声",comfort:5,effect:"人类来访概率 +60%",attract:"human",power:3,cost:{coins:24}},
 {id:"teaset",name:"雾气茶具",icon:"🍵",note:"总能倒出客人最怀念的味道",comfort:5,effect:"所有客人的基础报酬 +2",reward:2,cost:{item:"银线",amount:4}}
];
const DEFAULT_STATE={day:1,coins:12,inventory:{"捕风瓶":1,"月光碎片":2,"空玻璃瓶":1,"银线":2,"旧木片":2,"萤火粉":1,"铜齿轮":1,"夜鸦羽毛":1},history:[],relationships:{},decor:[],resolved:false,currentCustomer:1};
let state=load();
function clone(v){return JSON.parse(JSON.stringify(v))}
function load(){try{const old=JSON.parse(localStorage.getItem("late-lantern-save")||"null")||{};return {...clone(DEFAULT_STATE),...old,inventory:{...DEFAULT_STATE.inventory,...(old.inventory||{})},relationships:old.relationships||{},decor:old.decor||[],currentCustomer:Number.isInteger(old.currentCustomer)?old.currentCustomer:(old.day||1)*5%CUSTOMERS.length}}catch{return clone(DEFAULT_STATE)}}
function save(){localStorage.setItem("late-lantern-save",JSON.stringify(state))}
function relation(name){if(!state.relationships[name])state.relationships[name]={favor:0,visits:0,deals:0};return state.relationships[name]}
function dailyCustomer(){return CUSTOMERS[state.currentCustomer]}
function ownedDecor(){return DECOR.filter(d=>state.decor.includes(d.id))}
function chooseCustomer(){const weighted=CUSTOMERS.flatMap((c,i)=>{const favorWeight=Math.floor(relation(c.name).favor/2),decorWeight=ownedDecor().filter(d=>d.attract===c.group).reduce((n,d)=>n+d.power,0);return Array(2+favorWeight+decorWeight).fill(i)});state.currentCustomer=weighted[Math.floor(Math.random()*weighted.length)]}
function count(name){return state.inventory[name]||0}
function canCraft(item){return Object.entries(ITEMS[item].recipe).every(([name,n])=>count(name)>=n)}
function reward(c){const favor=relation(c.name).favor,decorBonus=ownedDecor().reduce((n,d)=>n+(d.reward||0),0),comfortBonus=Math.floor(ownedDecor().reduce((n,d)=>n+d.comfort,0)/10);const bonus=c.pay.type==="coins"?Math.floor(favor/3)*2+decorBonus+comfortBonus:Math.floor(favor/4)+Math.floor((decorBonus+comfortBonus)/2);return {...c.pay,amount:c.pay.amount+bonus}}
function rewardLabel(c){const r=reward(c);return r.type==="coins"?`${r.amount} 枚铜币`:`${r.amount} × ${r.item}`}
function showPage(id){document.querySelectorAll(".game-page").forEach(p=>p.classList.toggle("active",p.id===`page-${id}`));document.querySelectorAll(".main-nav .nav-link").forEach(b=>b.classList.toggle("active",b.dataset.page===id));location.hash=id;scrollTo({top:0,behavior:"smooth"})}
function render(){
 const c=dailyCustomer(),rel=relation(c.name),has=count(c.item)>0,craftable=canCraft(c.item);
 document.querySelector("#dayNumber").textContent=state.day;document.querySelector("#coinCount").textContent=state.coins;document.querySelector("#portraitIcon").textContent=c.icon;document.querySelector("#customerKind").textContent=c.kind;document.querySelector("#customerName").textContent=c.name;document.querySelector("#customerTrait").textContent=c.trait;document.querySelector("#customerStory").textContent=c.story;document.querySelector("#requestedItem").textContent=c.item;document.querySelector("#paymentOffer").textContent=rewardLabel(c);document.querySelector("#currentFavor").textContent=rel.favor;document.querySelector("#favorHearts").textContent="♥".repeat(Math.min(5,Math.ceil(rel.favor/2)))+"♡".repeat(Math.max(0,5-Math.ceil(rel.favor/2)));
 document.querySelector("#availabilityText").textContent=has?"货架上正好有这件物品":craftable?"没有成品，但材料齐全":"货架上没有，材料也不足";document.querySelector(".dot").style.background=has?"#64715d":craftable?"#c79346":"#a5402d";document.querySelector("#sellButton").disabled=!has||state.resolved;document.querySelector("#craftButton").disabled=!craftable||has||state.resolved;document.querySelector("#refuseButton").disabled=state.resolved;document.querySelector("#craftCost").innerHTML=`<small>${Object.entries(ITEMS[c.item].recipe).map(([n,q])=>`${n}×${q}`).join(" · ")}</small>`;
 renderInventory();renderRelationships();renderHistory();renderShop();save();
}
function renderInventory(){const names=[...Object.keys(ITEMS),...Object.keys(MATERIALS)];document.querySelector("#inventoryGrid").innerHTML=names.map(name=>{const d=ITEMS[name]||MATERIALS[name],q=count(name);return `<article class="item ${q?"":"empty"}"><span class="item-count">${q}</span><span class="item-icon">${d.icon}</span><span class="item-name">${name}</span><span class="item-note">${d.note}</span></article>`}).join("")}
function renderRelationships(){document.querySelector("#relationshipGrid").innerHTML=CUSTOMERS.map(c=>{const r=relation(c.name),level=r.favor>=8?"知己":r.favor>=4?"熟客":r.favor?"相识":"未曾谋面";return `<article class="relation-card ${r.visits?"":"unknown"}"><span class="relation-icon">${r.visits?c.icon:"?"}</span><div><span class="tag">${r.visits?c.kind:"身份未知"}</span><h3>${r.visits?c.name:"尚未到访的客人"}</h3><p>${level} · 来访 ${r.visits} 次 · 成交 ${r.deals} 次</p><div class="favor-bar"><i style="width:${Math.min(100,r.favor*10)}%"></i></div><small>好感 ${r.favor}/10</small></div></article>`}).join("")}
function renderHistory(){document.querySelector("#historyList").innerHTML=state.history.length?state.history.map(h=>`<div class="history-row"><span class="history-day">第 ${h.day} 日</span><span>${h.story}</span><span class="history-outcome">${h.outcome}</span></div>`).join(""):`<div class="history-row"><span class="history-day">开店前</span><span>你擦亮门上的铜铃，等待第一个故事。</span><span class="history-outcome">尚无记录</span></div>`}
function costLabel(d){return d.cost.coins?`${d.cost.coins} 枚铜币`:`${d.cost.amount} × ${d.cost.item}`}
function canBuy(d){return d.cost.coins?state.coins>=d.cost.coins:count(d.cost.item)>=d.cost.amount}
function renderShop(){const owned=ownedDecor();document.querySelector("#comfortScore").textContent=owned.reduce((n,d)=>n+d.comfort,0);document.querySelector("#decorLayer").innerHTML=owned.map(d=>`<span class="placed-decor decor-${d.id}" title="${d.name}">${d.id==="rug"?"":d.icon}</span>`).join("");document.querySelector("#decorGrid").innerHTML=DECOR.map(d=>{const bought=state.decor.includes(d.id);return `<article class="decor-card ${bought?"owned":""}"><span class="decor-icon">${d.icon}</span><div><h3>${d.name}</h3><p>${d.note}</p><div class="effect-tag">✦ ${d.effect}</div><small>温暖度 +${d.comfort}</small></div><button class="button ${bought?"ghost":"primary"}" data-buy="${d.id}" ${bought||!canBuy(d)?"disabled":""}>${bought?"已添置":costLabel(d)}</button></article>`}).join("");document.querySelectorAll("[data-buy]").forEach(b=>b.addEventListener("click",()=>buyDecor(b.dataset.buy)))}
function buyDecor(id){const d=DECOR.find(x=>x.id===id);if(!d||state.decor.includes(id)||!canBuy(d))return;if(d.cost.coins)state.coins-=d.cost.coins;else state.inventory[d.cost.item]-=d.cost.amount;state.decor.push(id);save();render();document.querySelector("#noticeTitle").textContent=`添置了${d.name}`;document.querySelector("#noticeText").textContent=`${d.note}。店铺温暖度增加了 ${d.comfort} 点。`;document.querySelector("#noticeDialog").showModal()}
function complete(action){const c=dailyCustomer(),rel=relation(c.name);let title,text,label,icon="✦",outcome;if(action==="craft"){for(const [n,q] of Object.entries(ITEMS[c.item].recipe))state.inventory[n]-=q;state.inventory[c.item]=(state.inventory[c.item]||0)+1;save();render();document.querySelector("#availabilityText").textContent="制作完成，可以交给客人了";return}rel.visits+=1;if(action==="sell"){const r=reward(c);state.inventory[c.item]-=1;if(r.type==="coins")state.coins+=r.amount;else state.inventory[r.item]=(state.inventory[r.item]||0)+r.amount;rel.favor=Math.min(10,rel.favor+2);rel.deals+=1;title="门铃轻轻响了两次";text=`${c.name}带着${c.item}离开了。你们的好感增加了 2 点。下次再来时，也许会带来更好的报酬。`;outcome=`售出「${c.item}」 · 好感 +2`;label="交易完成"}else{rel.favor=Math.max(0,rel.favor-1);title="有些故事不属于今晚";text=`你向${c.name}摇了摇头。客人把故事重新收好，消失在门外的夜色里。`;outcome="婉言拒绝 · 好感 -1";icon="☾";label="客人离开了"}state.resolved=true;state.history.unshift({day:state.day,story:`${c.name}来寻找${c.item}。`,outcome});save();render();showDialog(icon,label,title,text)}
function showDialog(icon,label,title,text){document.querySelector("#dialogIcon").textContent=icon;document.querySelector("#dialogLabel").textContent=label;document.querySelector("#dialogTitle").textContent=title;document.querySelector("#dialogText").textContent=text;document.querySelector("#resultDialog").showModal()}
function nextDay(){const pool=Object.keys(MATERIALS),gift=pool[Math.floor(Math.random()*pool.length)];state.day+=1;state.resolved=false;state.inventory[gift]=(state.inventory[gift]||0)+1;chooseCustomer();state.history.unshift({day:state.day,story:`清晨，门缝里出现了一份${gift}。`,outcome:"每日物品 +1"});save();document.querySelector("#resultDialog").close();render();showPage("visitor")}
document.querySelectorAll(".nav-link").forEach(b=>b.addEventListener("click",()=>showPage(b.dataset.page)));document.querySelector("#sellButton").addEventListener("click",()=>complete("sell"));document.querySelector("#craftButton").addEventListener("click",()=>complete("craft"));document.querySelector("#refuseButton").addEventListener("click",()=>complete("refuse"));document.querySelector("#nextDayButton").addEventListener("click",nextDay);document.querySelector("#noticeClose").addEventListener("click",()=>document.querySelector("#noticeDialog").close());document.querySelector("#resetButton").addEventListener("click",()=>{if(confirm("要清除所有故事、关系和陈设，重新开店吗？")){state=clone(DEFAULT_STATE);save();render();showPage("visitor")}});
render();showPage(["visitor","inventory","ledger","shop"].includes(location.hash.slice(1))?location.hash.slice(1):"visitor");
