const CHAPTERS=[{id:1,start:1,name:"初燃的灯",note:"门铃第一次为陌生的故事响起"},{id:2,start:8,name:"雾中的街",note:"雾散开后，迟灯巷比从前更长了"},{id:3,start:15,name:"星落之夜",note:"天上的旧星开始寻找遗失之物"}];
const LEGACY_VISIT_RULES={
 "栗尾先生":[{favor:0,weekday:[3],label:"每周三"},{favor:4,season:["summer"],label:"好感 4：夏季也会来"}],
 "阿墨":[{favor:0,moon:["full"],label:"满月之夜"},{favor:0,weekday:[6],label:"每周六"},{favor:5,season:["autumn"],label:"好感 5：秋季也会来"}],
 "雨巷邮差":[{favor:0,season:["spring"],label:"春季"},{favor:4,month:[2],label:"好感 4：每季第二个月"}],
 "钟婆婆":[{favor:0,weekday:[1],label:"每周一"},{favor:5,season:["winter"],label:"好感 5：冬季也会来"}],
 "瞌睡的獾":[{favor:0,season:["winter"],label:"冬季"},{favor:3,moon:["new"],label:"好感 3：新月之夜"}],
 "没有影子的小姐":[{favor:0,moon:["new"],label:"新月之夜"},{favor:0,weekday:[5],label:"每周五"},{favor:6,season:["winter"],label:"好感 6：冬季也会来"}],
 "贝壳里的男孩":[{favor:0,season:["summer"],label:"夏季"},{favor:0,weekday:[7],label:"每周日"},{favor:4,month:[1],label:"好感 4：每季第一个月"}],
 "雾鹿女士":[{favor:0,season:["autumn"],moon:["full"],label:"秋季的满月"},{favor:0,weekday:[2],label:"每周二"},{favor:5,season:["autumn"],label:"好感 5：整个秋季"}],
 "失眠的云":[{favor:0,month:[2],label:"每季第二个月"},{favor:4,moon:["waning"],label:"好感 4：亏月期间"}],
 "北斗船长":[{favor:0,season:["spring"],month:[3],label:"春季第三个月"},{favor:0,weekday:[4],label:"每周四"},{favor:5,moon:["waxing"],label:"好感 5：盈月期间"}],
 "衔火的蛾":[{favor:0,season:["summer"],moon:["full"],label:"夏季的满月"},{favor:5,season:["summer"],label:"好感 5：整个夏季"}],
 "最后一颗星":[{favor:0,season:["winter"],moon:["new"],label:"冬季的新月"},{favor:7,season:["winter"],label:"好感 7：整个冬季"}]
};
const LEGACY_ITEMS={"捕风瓶":{chapter:1,icon:"🏺",note:"瓶口偶尔传来口哨声",recipe:{"月光碎片":1,"空玻璃瓶":1}}};
const LEGACY_MATERIALS={"月光碎片":{chapter:1,icon:"🌙",note:"薄而冷的微光"}};
Object.assign(LEGACY_ITEMS,{
 "无声剪刀":{chapter:1,icon:"✂️",note:"剪开布匹时像影子一样安静",recipe:{"银线":1,"旧木片":1}},
 "温度墨水":{chapter:2,icon:"🖋️",note:"写下的字摸起来像一双手",recipe:{"月光碎片":1,"雾盐":1}},
 "遗忘粉笔":{chapter:3,icon:"🧑‍🏫",note:"只擦去别人强加的坏话",recipe:{"星砂":1,"记忆蜡":1}},
 "钥匙糖":{chapter:2,icon:"🍬",note:"含在嘴里会想起一扇门",recipe:{"雾盐":1,"月光碎片":1}},
 "水面鞋":{chapter:3,icon:"👞",note:"鞋底踩在世界的倒面",recipe:{"银线":2,"星砂":1}},
 "不融冰":{chapter:2,icon:"🧊",note:"只有回到故乡才会融化",recipe:{"雾盐":2,"月光碎片":1}},
 "归巢铃":{chapter:3,icon:"🔔",note:"无论多远都能听见家的方向",recipe:{"铜齿轮":1,"回声贝壳":1}},
 "慢时喷壶":{chapter:3,icon:"🚿",note:"浇过的地方会慢慢长大",recipe:{"铜齿轮":1,"雾盐":2}},
 "逆流梳":{chapter:3,icon:"🪮",note:"能把河水梳回源头",recipe:{"回声贝壳":1,"银线":2}},
 "月文字帖":{chapter:3,icon:"📜",note:"字迹只在月光下显现",recipe:{"星砂":1,"月光碎片":2}},
 "星火盐罐":{chapter:3,icon:"🏺",note:"一小撮就能调味一锅星云",recipe:{"星砂":2,"雾盐":1}},
 "黄昏骰子":{chapter:3,icon:"🎲",note:"掷出的不是点数，而是一条路",recipe:{"记忆蜡":1,"铜齿轮":1,"星砂":1}}
});
const ITEMS=window.GAME_ITEMS;
const MATERIALS=window.GAME_MATERIALS;
const MATERIAL_GROUPS=window.MATERIAL_CATEGORIES;
const ENVIRONMENT=window.ENVIRONMENT_CONFIG;
const LEGACY_CUSTOMERS=[
 {name:"栗尾先生",group:"beast",kind:"兽客 · 狐狸",icon:"🦊",trait:"说话时总要先摸摸帽檐",item:"捕风瓶",story:"我替森林里的鸟儿保管歌声。昨晚有一支歌从盒中逃了出去，藏进了北风里。没有那支歌，知更鸟就等不到春天。",pay:{type:"coins",amount:7,item:null}},
 {name:"阿墨",group:"beast",kind:"兽客 · 乌鸦",icon:"🐦‍⬛",trait:"右眼戴着一枚黄铜单片镜",item:"不撒谎的镜子",story:"我的收藏里有三百七十二件闪亮的东西，却没有一件肯告诉我，我到底是不是一只好鸟。",pay:{type:"item",amount:3,item:"夜鸦羽毛"}},
 {name:"雨巷邮差",group:"night",kind:"夜行人",icon:"🧥",trait:"衣角一直滴着并不存在的雨",item:"雨天火柴",story:"有一封信在我的包里睡了二十年。收信人住在一条只会在雨夜出现的街上，我需要一点火光认路。",pay:{type:"coins",amount:10,item:null}},
 {name:"钟婆婆",group:"human",kind:"人类 · 钟表匠",icon:"👵",trait:"口袋里有许多细小的滴答声",item:"倒着走的怀表",story:"孙女第一次叫我奶奶的时候，我正忙着修钟，没来得及答应。只要一分钟，我想回去好好听一次。",pay:{type:"item",amount:4,item:"铜齿轮"}},
 {name:"瞌睡的獾",group:"beast",kind:"兽客 · 獾",icon:"🦡",trait:"每说三句话就打一个哈欠",item:"梦境纽扣",story:"我做了一个很长的梦，梦里花园永远是春天。最近梦的边缘开线了，你能帮我把它缝好吗？",pay:{type:"coins",amount:6,item:null}},
 {name:"没有影子的小姐",chapter:1,group:"night",kind:"身份不明",icon:"🎭",trait:"站在灯下，脚边仍空空如也",item:"影子雨伞",story:"我的影子离家出走了。它说除非我学会一个人散步，否则永远不回来。可街上的目光太亮了。",pay:{type:"item",amount:3,item:"月光碎片"}},
 {name:"贝壳里的男孩",chapter:2,group:"human",kind:"人类 · 来自海边",icon:"👦",trait:"耳边总有很远的潮声",item:"回声口琴",story:"奶奶临走前说了一句话，可浪太大，我没有听清。听说这种口琴能把错过的话再吹回来一次。",pay:{type:"item",amount:3,item:"回声贝壳"}},
 {name:"雾鹿女士",chapter:2,group:"beast",kind:"兽客 · 白鹿",icon:"🦌",trait:"鹿角之间浮着一小团晨雾",item:"雾路提灯",story:"我的鹿群误入了没有路标的白雾。它们都相信我认得归途，可其实我也已经迷路很久了。",pay:{type:"coins",amount:14,item:null}},
 {name:"失眠的云",chapter:2,group:"night",kind:"异客 · 云",icon:"☁️",trait:"说话时有细雨落在柜台上",item:"借梦枕",story:"城市里的梦太吵了，我已经三个月没有好好睡过。能不能借我一个安静得只剩风声的梦？",pay:{type:"item",amount:3,item:"雾盐"}},
 {name:"北斗船长",chapter:3,group:"human",kind:"人类 · 星海船长",icon:"🧑‍✈️",trait:"大衣上沾着几粒不会融化的星",item:"星图罗盘",story:"我的船从天空的裂缝掉了下来。船员还在星海上等我，我得在下一次月蚀前找到回去的方向。",pay:{type:"coins",amount:20,item:null}},
 {name:"衔火的蛾",chapter:3,group:"beast",kind:"兽客 · 月蛾",icon:"🦋",trait:"翅膀边缘闪着银蓝色火花",item:"记忆蜡烛",story:"我们一生只能看见一次真正的火。我想在生命结束以前，把那束光留给还没破茧的孩子。",pay:{type:"item",amount:3,item:"星砂"}},
 {name:"最后一颗星",chapter:3,group:"night",kind:"异客 · 星辰",icon:"⭐",trait:"它的声音像很远处的玻璃铃",item:"黎明信封",story:"天亮之后，人们就不会再记得我曾经来过。请替我把这封告别信寄给每一个曾在夜里许愿的人。",pay:{type:"item",amount:3,item:"记忆蜡"}}
];
const CUSTOMERS=window.GAME_VISITORS;
const VISIT_RULES=Object.fromEntries(CUSTOMERS.map(visitor=>[visitor.name,visitor.schedule]));
const CATEGORY_NAMES=window.VISITOR_CATEGORIES;
const DECOR=[
 {id:"lamp",name:"萤火吊灯",icon:"🏮",note:"用瓶中的萤火照亮柜台",comfort:2,effect:"夜行异客与星辰来访概率 +40%",attract:["night","astral"],power:2,cost:{coins:8}},
 {id:"plant",name:"会打哈欠的盆栽",icon:"🪴",note:"夜深时会自己缩进花盆",comfort:2,effect:"兽客与自然灵来访概率 +40%",attract:["beast","nature"],power:2,cost:{item:"月光碎片",amount:2}},
 {id:"rug",name:"星河地毯",icon:"✦",note:"织纹会随着夜色缓慢流动",comfort:3,effect:"吸引远方旅人，基础报酬 +1",attract:["traveler"],power:2,reward:1,cost:{coins:14}},
 {id:"cat",name:"看店黑猫",icon:"🐈‍⬛",note:"它自称不是店员，只是碰巧在此",comfort:4,effect:"兽客来访概率 +60%",attract:"beast",power:3,cost:{item:"夜鸦羽毛",amount:3}},
 {id:"clock",name:"十三点钟",icon:"🕰️",note:"每天会多敲一次不存在的钟声",comfort:5,effect:"人类来访概率 +60%",attract:"human",power:3,cost:{coins:24}},
 {id:"teaset",name:"雾气茶具",icon:"🍵",note:"总能倒出客人最怀念的味道",comfort:5,effect:"所有客人的基础报酬 +2",reward:2,cost:{item:"银线",amount:4}}
];
const DEFAULT_STATE={day:1,coins:12,inventory:{"月光碎片":2,"空玻璃瓶":1,"银线":2,"旧木片":2,"萤火粉":1,"铜齿轮":1,"夜鸦羽毛":1},history:[],relationships:{},decor:[],discoveredItems:[],metCustomers:[],environmentDay:0,weather:null,dailyDrops:[],resolved:false,currentCustomer:1};
let state=load();
function clone(v){return JSON.parse(JSON.stringify(v))}
function load(){try{const old=JSON.parse(localStorage.getItem("late-lantern-save")||"null")||{},known=old.discoveredItems||Object.keys(old.inventory||{}).filter(n=>GAME_ITEMS[n]),met=old.metCustomers||Object.entries(old.relationships||{}).filter(([,r])=>r.visits>0).map(([name])=>name);return {...clone(DEFAULT_STATE),...old,inventory:{...DEFAULT_STATE.inventory,...(old.inventory||{})},relationships:old.relationships||{},decor:old.decor||[],discoveredItems:known,metCustomers:met,dailyDrops:old.dailyDrops||[],currentCustomer:Number.isInteger(old.currentCustomer)?old.currentCustomer:(old.day||1)*5%CUSTOMERS.length}}catch{return clone(DEFAULT_STATE)}}
function save(){localStorage.setItem("late-lantern-save",JSON.stringify(state))}
function relation(name){if(!state.relationships[name])state.relationships[name]={favor:0,visits:0,deals:0};return state.relationships[name]}
function dailyCustomer(){return CUSTOMERS[state.currentCustomer]}
function calendar(day=state.day){const n=day-1,moonDay=n%28+1,month=Math.floor(n/28)%12+1,seasonIndex=Math.floor((month-1)/3),seasonKeys=["spring","summer","autumn","winter"],seasonNames=["春季","夏季","秋季","冬季"],phaseIndex=moonDay===1||moonDay===28?0:moonDay<=4?1:moonDay<=7?2:moonDay<=13?3:moonDay<=16?4:moonDay<=20?5:moonDay<=23?6:7,phaseIcons=["🌑","🌒","🌓","🌔","🌕","🌖","🌗","🌘"],phaseNames=["新月","娥眉月","上弦月","盈凸月","满月","亏凸月","下弦月","残月"],moonGroup=moonDay===1||moonDay===28?"new":moonDay>=14&&moonDay<=16?"full":moonDay<14?"waxing":"waning";return {weekday:n%7+1,moonDay,month,monthInSeason:(month-1)%3+1,season:seasonKeys[seasonIndex],seasonName:seasonNames[seasonIndex],year:Math.floor(n/336)+1,phaseIcon:phaseIcons[phaseIndex],phaseName:phaseNames[phaseIndex],moonGroup}}
function ruleMatches(rule,cal=calendar()){return (!rule.weekday||rule.weekday.includes(cal.weekday))&&(!rule.season||rule.season.includes(cal.season))&&(!rule.month||rule.month.includes(cal.monthInSeason))&&(!rule.moon||rule.moon.includes(cal.moonGroup))&&(!rule.weather||rule.weather.includes(state.weather?.id))}
function activeVisitRules(c){const favor=relation(c.name).favor;return (VISIT_RULES[c.name]||[{favor:0,label:"任何日子"}]).filter(r=>favor>=r.favor)}
function canVisitToday(c){return activeVisitRules(c).some(rule=>ruleMatches(rule))}
function currentChapter(){return [...CHAPTERS].reverse().find(c=>state.day>=c.start)}
function chapterNumber(){return currentChapter().id}
function unlockedCustomers(){return CUSTOMERS.filter(c=>(c.chapter||1)<=chapterNumber())}
function ownedDecor(){return DECOR.filter(d=>state.decor.includes(d.id))}
function eligibleCustomersToday(){const eligible=unlockedCustomers().filter(canVisitToday);return eligible.length?eligible:unlockedCustomers()}
function chooseCustomer(){const weighted=eligibleCustomersToday().flatMap(c=>{const i=CUSTOMERS.indexOf(c),favorWeight=Math.floor(relation(c.name).favor/2),decorWeight=ownedDecor().filter(d=>Array.isArray(d.attract)?d.attract.includes(c.category):d.attract===c.category).reduce((n,d)=>n+d.power,0);return Array(2+favorWeight+decorWeight).fill(i)});state.currentCustomer=weighted[Math.floor(Math.random()*weighted.length)]}
function count(name){return state.inventory[name]||0}
function isDiscovered(item){return state.discoveredItems.includes(item)}
function discoverCurrentRequest(){const item=dailyCustomer().item;if(!isDiscovered(item))state.discoveredItems.push(item)}
function markCurrentMet(){const name=dailyCustomer().name;if(!state.metCustomers.includes(name))state.metCustomers.push(name)}
function canCraft(item){return isDiscovered(item)&&Object.entries(ITEMS[item].recipe).every(([name,n])=>count(name)>=n)}
function weightedPick(list){let roll=Math.random()*list.reduce((n,x)=>n+x.weight,0);for(const entry of list){roll-=entry.weight;if(roll<=0)return entry}return list[list.length-1]}
function generateWeather(cal=calendar()){return clone(weightedPick(ENVIRONMENT.weather[cal.season]))}
function generateDrops(cal=calendar()){const candidates=new Map();for(const rule of ENVIRONMENT.drops){if(rule.season&&rule.season!==cal.season)continue;if(rule.weather&&rule.weather!==state.weather.id)continue;if(rule.moon&&rule.moon!==cal.moonGroup)continue;for(const name of rule.items)candidates.set(name,Math.max(candidates.get(name)||0,rule.chance))}const pool=[...candidates.entries()].map(([name,chance])=>({name,chance})),guaranteed=pool[Math.floor(Math.random()*pool.length)],picked=[guaranteed];for(const entry of pool){if(entry!==guaranteed&&picked.length<3&&Math.random()<entry.chance)picked.push(entry)}return picked.map(x=>({name:x.name,amount:1}))}
function ensureDailyEnvironment(){if(state.environmentDay===state.day&&state.weather&&state.dailyDrops.length)return;const cal=calendar();state.weather=generateWeather(cal);state.dailyDrops=generateDrops(cal);state.environmentDay=state.day;for(const drop of state.dailyDrops)state.inventory[drop.name]=(state.inventory[drop.name]||0)+drop.amount;state.history.unshift({day:state.day,story:`${state.weather.icon} ${state.weather.name}。清晨在店门口发现了${state.dailyDrops.map(d=>`${d.name}×${d.amount}`).join("、")}。`,outcome:"环境掉落"});save()}
function reward(c){const favor=relation(c.name).favor,decorBonus=ownedDecor().reduce((n,d)=>n+(d.reward||0),0),comfortBonus=Math.floor(ownedDecor().reduce((n,d)=>n+d.comfort,0)/10);const bonus=c.pay.type==="coins"?Math.floor(favor/3)*2+decorBonus+comfortBonus:Math.floor(favor/4)+Math.floor((decorBonus+comfortBonus)/2);return {...c.pay,amount:c.pay.amount+bonus}}
function rewardLabel(c){const r=reward(c);return r.type==="coins"?`${r.amount} 枚铜币`:`${r.amount} × ${r.item}`}
function showPage(id){document.querySelectorAll(".game-page").forEach(p=>p.classList.toggle("active",p.id===`page-${id}`));document.querySelectorAll(".main-nav .nav-link").forEach(b=>b.classList.toggle("active",b.dataset.page===id));location.hash=id;scrollTo({top:0,behavior:"smooth"})}
function render(){
 const c=dailyCustomer(),rel=relation(c.name),has=count(c.item)>0,craftable=canCraft(c.item),cal=calendar();
 const chapter=currentChapter(),next=CHAPTERS.find(x=>x.id===chapter.id+1),span=next?next.start-chapter.start:7,progress=next?Math.min(100,((state.day-chapter.start+1)/span)*100):100;
 document.querySelector("#chapterBadge").textContent=`第${["一","二","三"][chapter.id-1]}章`;document.querySelector("#chapterName").textContent=`第${["一","二","三"][chapter.id-1]}章 · ${chapter.name}`;document.querySelector("#chapterHint").textContent=next?`距离「${next.name}」还有 ${next.start-state.day} 天`:"所有章节已经解锁 · 故事仍会继续";document.querySelector("#chapterProgress").style.width=`${progress}%`;
 document.querySelector("#dayNumber").textContent=state.day;document.querySelector("#coinCount").textContent=state.coins;document.querySelector(".moon").textContent=cal.phaseIcon;document.querySelector("#calendarMoon").textContent=cal.phaseIcon;document.querySelector("#moonName").textContent=`${cal.phaseName} · 第 ${cal.moonDay} 夜`;document.querySelector("#seasonName").textContent=cal.seasonName;document.querySelector("#monthName").textContent=`${cal.seasonName[0]}${["一","二","三"][cal.monthInSeason-1]}月`;document.querySelector("#weekdayName").textContent=`星期${["一","二","三","四","五","六","日"][cal.weekday-1]}`;document.querySelector("#weatherName").textContent=`${state.weather.icon} ${state.weather.name}`;document.querySelector("#calendarDate").textContent=`第 ${cal.year} 年 · 第 ${cal.month} 月`;document.querySelector("#dailyDropList").innerHTML=state.dailyDrops.map(d=>`<span><b>${MATERIALS[d.name].icon}</b>${d.name}<small>+${d.amount}</small></span>`).join("");document.querySelector("#windowMoon").textContent=cal.phaseIcon;document.querySelector("#windowSky").textContent=`${cal.seasonName} · ${cal.phaseName} · ${state.weather.name}`;document.querySelector("#room").dataset.season=cal.season;
 document.querySelector("#portraitIcon").textContent=c.icon;document.querySelector("#customerKind").textContent=c.kind;document.querySelector("#customerName").textContent=c.name;document.querySelector("#customerTrait").textContent=c.trait;document.querySelector("#customerStory").textContent=c.story;document.querySelector("#requestedItem").textContent=c.item;document.querySelector("#paymentOffer").textContent=rewardLabel(c);document.querySelector("#currentFavor").textContent=rel.favor;document.querySelector("#favorHearts").textContent="♥".repeat(Math.min(5,Math.ceil(rel.favor/2)))+"♡".repeat(Math.max(0,5-Math.ceil(rel.favor/2)));
 document.querySelector("#availabilityText").textContent=has?"货架上正好有这件物品":craftable?"没有成品，但材料齐全":"货架上没有，材料也不足";document.querySelector(".dot").style.background=has?"#64715d":craftable?"#c79346":"#a5402d";document.querySelector("#sellButton").disabled=!has||state.resolved;document.querySelector("#craftButton").disabled=!craftable||has||state.resolved;document.querySelector("#refuseButton").disabled=state.resolved;document.querySelector("#craftCost").innerHTML=`<small>${Object.entries(ITEMS[c.item].recipe).map(([n,q])=>`${n}×${q}`).join(" · ")}</small>`;
 renderForecast();renderInventory();renderQuickInventory();renderRelationships();renderHistory();renderShop();save();
}
function renderForecast(){const chosen=dailyCustomer(),pool=eligibleCustomersToday(),candidates=pool.some(c=>c.name===chosen.name)?pool:[chosen,...pool];document.querySelector("#forecastCount").textContent=`${candidates.length} 位符合条件 · 最终只会来一位`;document.querySelector("#potentialVisitors").innerHTML=candidates.map(c=>{const selected=c.name===chosen.name,met=state.metCustomers.includes(c.name);return `<article class="forecast-person ${selected?"selected":"not-selected"}"><span class="forecast-avatar">${met?c.icon:"?"}</span><div><small>${selected?"今晚来访":"今夜未出现"}</small><strong>${met?c.name:"未知的客人"}</strong><em>${met?CATEGORY_NAMES[c.category]:"尚未结识"}</em></div>${selected?"<i>✓</i>":""}</article>`}).join("")}
function inventoryCard(name,d){const q=count(name);return `<article class="item ${q?"":"empty"}"><span class="item-count">${q}</span><span class="item-icon">${d.icon}</span><span class="item-name">${name}</span><span class="item-note">${d.note}</span></article>`}
function renderInventory(){const products=Object.entries(ITEMS).filter(([name])=>isDiscovered(name));const productSection=`<section class="inventory-group products"><header><div><p class="eyebrow">FINISHED GOODS</p><h2>已发现的奇异商品</h2></div><span>${products.length} / ${Object.keys(ITEMS).length} 种配方已发现</span></header><div class="inventory-grid-inner">${products.map(([n,d])=>inventoryCard(n,d)).join("")}</div></section>`;const materialSections=Object.entries(MATERIAL_GROUPS).map(([key,group])=>{const entries=Object.entries(MATERIALS).filter(([,d])=>d.category===key);return `<section class="inventory-group" style="--group-color:${group.color}"><header><div><p class="eyebrow">${key.toUpperCase()}</p><h2>${group.name}</h2></div><span>${group.note}</span></header><div class="inventory-grid-inner">${entries.map(([n,d])=>inventoryCard(n,d)).join("")}</div></section>`}).join("");document.querySelector("#inventoryGrid").innerHTML=productSection+materialSections}
function renderQuickInventory(){const entries=[...Object.entries(ITEMS).filter(([n])=>isDiscovered(n)),...Object.entries(MATERIALS)].filter(([n])=>count(n)>0),total=entries.reduce((n,[name])=>n+count(name),0);document.querySelector("#quickInventoryCount").textContent=`${total} 件库存`;document.querySelector("#quickInventory").innerHTML=entries.length?`<div class="quick-grid">${entries.map(([name,d])=>`<span class="quick-item"><b>${d.icon}</b><em>${name}</em><small>×${count(name)}</small></span>`).join("")}</div><button class="text-button quick-more" data-page="inventory">查看完整货架 →</button>`:`<p class="quick-empty">货架上暂时空空如也。</p>`;document.querySelector("#quickInventory [data-page]")?.addEventListener("click",()=>showPage("inventory"))}
function relationshipCard(c){const locked=c.chapter>chapterNumber(),r=relation(c.name),met=state.metCustomers.includes(c.name),level=r.favor>=8?"知己":r.favor>=4?"熟客":r.favor?"相识":"初见";if(locked)return `<article class="relation-card locked"><span class="relation-icon">⌛</span><div><span class="tag">第 ${c.chapter} 章解锁</span><h3>尚未写下的名字</h3><p>迟灯巷的雾还没有散到那里。</p></div></article>`;if(!met)return `<article class="relation-card unknown"><span class="relation-icon">?</span><div><span class="tag">${CATEGORY_NAMES[c.category]}</span><h3>尚未到访的客人</h3><p>第一次见面后，来访规律会记录在这里。</p></div></article>`;const rules=VISIT_RULES[c.name]||[],ruleHtml=rules.map(rule=>`<span class="schedule-chip ${r.favor>=rule.favor?"active":"locked-rule"}">${r.favor>=rule.favor?"◉":"◇"} ${rule.label}</span>`).join("");return `<article class="relation-card"><span class="relation-icon">${c.icon}</span><div><span class="tag">${c.kind}</span><h3>${c.name}</h3><p>${level} · 完成来访 ${r.visits} 次 · 成交 ${r.deals} 次</p><div class="visit-schedule">${ruleHtml}</div><div class="favor-bar"><i style="width:${Math.min(100,r.favor*10)}%"></i></div><small>好感 ${r.favor}/10</small></div></article>`}
function renderRelationships(){document.querySelector("#relationshipGrid").innerHTML=Object.entries(CATEGORY_NAMES).map(([key,label])=>{const visitors=CUSTOMERS.filter(c=>c.category===key),known=visitors.filter(c=>state.metCustomers.includes(c.name)).length;return `<section class="visitor-group"><header><div><p class="eyebrow">${key.toUpperCase()}</p><h2>${label}</h2></div><span>${known} / ${visitors.length} 已结识</span></header><div class="relationship-grid-inner">${visitors.map(relationshipCard).join("")}</div></section>`}).join("")}
function renderHistory(){document.querySelector("#historyList").innerHTML=state.history.length?state.history.map(h=>`<div class="history-row"><span class="history-day">第 ${h.day} 日</span><span>${h.story}</span><span class="history-outcome">${h.outcome}</span></div>`).join(""):`<div class="history-row"><span class="history-day">开店前</span><span>你擦亮门上的铜铃，等待第一个故事。</span><span class="history-outcome">尚无记录</span></div>`}
function costLabel(d){return d.cost.coins?`${d.cost.coins} 枚铜币`:`${d.cost.amount} × ${d.cost.item}`}
function canBuy(d){return d.cost.coins?state.coins>=d.cost.coins:count(d.cost.item)>=d.cost.amount}
function renderShop(){const owned=ownedDecor();document.querySelector("#comfortScore").textContent=owned.reduce((n,d)=>n+d.comfort,0);document.querySelector("#decorLayer").innerHTML=owned.map(d=>`<span class="placed-decor decor-${d.id}" title="${d.name}">${d.id==="rug"?"":d.icon}</span>`).join("");document.querySelector("#decorGrid").innerHTML=DECOR.map(d=>{const bought=state.decor.includes(d.id);return `<article class="decor-card ${bought?"owned":""}"><span class="decor-icon">${d.icon}</span><div><h3>${d.name}</h3><p>${d.note}</p><div class="effect-tag">✦ ${d.effect}</div><small>温暖度 +${d.comfort}</small></div><button class="button ${bought?"ghost":"primary"}" data-buy="${d.id}" ${bought||!canBuy(d)?"disabled":""}>${bought?"已添置":costLabel(d)}</button></article>`}).join("");document.querySelectorAll("[data-buy]").forEach(b=>b.addEventListener("click",()=>buyDecor(b.dataset.buy)))}
function buyDecor(id){const d=DECOR.find(x=>x.id===id);if(!d||state.decor.includes(id)||!canBuy(d))return;if(d.cost.coins)state.coins-=d.cost.coins;else state.inventory[d.cost.item]-=d.cost.amount;state.decor.push(id);save();render();document.querySelector("#noticeLabel").textContent="店铺陈设";document.querySelector("#noticeTitle").textContent=`添置了${d.name}`;document.querySelector("#noticeText").textContent=`${d.note}。店铺温暖度增加了 ${d.comfort} 点。`;document.querySelector("#noticeDialog").showModal()}
function complete(action){const c=dailyCustomer(),rel=relation(c.name);let title,text,label,icon="✦",outcome;if(action==="craft"){for(const [n,q] of Object.entries(ITEMS[c.item].recipe))state.inventory[n]-=q;state.inventory[c.item]=(state.inventory[c.item]||0)+1;save();render();document.querySelector("#availabilityText").textContent="制作完成，可以交给客人了";return}rel.visits+=1;if(action==="sell"){const r=reward(c);state.inventory[c.item]-=1;if(r.type==="coins")state.coins+=r.amount;else state.inventory[r.item]=(state.inventory[r.item]||0)+r.amount;rel.favor=Math.min(10,rel.favor+2);rel.deals+=1;title="门铃轻轻响了两次";text=`${c.name}带着${c.item}离开了。你们的好感增加了 2 点。下次再来时，也许会带来更好的报酬。`;outcome=`售出「${c.item}」 · 好感 +2`;label="交易完成"}else{rel.favor=Math.max(0,rel.favor-1);title="有些故事不属于今晚";text=`你向${c.name}摇了摇头。客人把故事重新收好，消失在门外的夜色里。`;outcome="婉言拒绝 · 好感 -1";icon="☾";label="客人离开了"}state.resolved=true;state.history.unshift({day:state.day,story:`${c.name}来寻找${c.item}。`,outcome});save();render();showDialog(icon,label,title,text)}
function showDialog(icon,label,title,text){document.querySelector("#dialogIcon").textContent=icon;document.querySelector("#dialogLabel").textContent=label;document.querySelector("#dialogTitle").textContent=title;document.querySelector("#dialogText").textContent=text;document.querySelector("#resultDialog").showModal()}
function nextDay(){const oldChapter=chapterNumber();state.day+=1;state.resolved=false;ensureDailyEnvironment();const newChapter=chapterNumber();chooseCustomer();markCurrentMet();discoverCurrentRequest();if(newChapter>oldChapter){const chapter=currentChapter();state.history.unshift({day:state.day,story:`迟灯巷深处传来陌生的门铃声。`,outcome:`解锁第${["一","二","三"][newChapter-1]}章「${chapter.name}」`})}save();document.querySelector("#resultDialog").close();render();showPage("visitor");if(newChapter>oldChapter){const chapter=currentChapter();document.querySelector("#noticeLabel").textContent="新章节解锁";document.querySelector("#noticeTitle").textContent=`第${["一","二","三"][newChapter-1]}章 · ${chapter.name}`;document.querySelector("#noticeText").textContent=`${chapter.note}。新的客人、物品、材料与配方已经进入迟灯杂货铺。`;document.querySelector("#noticeDialog").showModal()}}
document.querySelectorAll(".nav-link").forEach(b=>b.addEventListener("click",()=>showPage(b.dataset.page)));document.querySelector("#sellButton").addEventListener("click",()=>complete("sell"));document.querySelector("#craftButton").addEventListener("click",()=>complete("craft"));document.querySelector("#refuseButton").addEventListener("click",()=>complete("refuse"));document.querySelector("#nextDayButton").addEventListener("click",nextDay);document.querySelector("#noticeClose").addEventListener("click",()=>document.querySelector("#noticeDialog").close());document.querySelector("#resetButton").addEventListener("click",()=>{if(confirm("要清除所有故事、关系和陈设，重新开店吗？")){state=clone(DEFAULT_STATE);ensureDailyEnvironment();markCurrentMet();discoverCurrentRequest();save();render();showPage("visitor")}});
ensureDailyEnvironment();markCurrentMet();discoverCurrentRequest();render();showPage(["visitor","inventory","ledger","shop"].includes(location.hash.slice(1))?location.hash.slice(1):"visitor");
